/**
 * SKETCHFAB-OPTIMIZED EXPORT SYSTEM
 * 
 * Comprehensive exporter designed for Sketchfab compatibility with:
 * - Multiple transparency modes (Alpha Mask, Blending, Dithered, Refraction)
 * - HD texture export (separate PNGs for 2D editing)
 * - Sketchfab-specific material metadata
 * - Open-source texture attribution (CC0 licenses)
 * 
 * Author: UUON Foundation Inc.
 * License: Proprietary with CC0 texture attributions
 */

import * as THREE from 'three';
import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter.js';
import { 
  generateShapeSpecificPBRTextures, 
  getCategoryFromShapeId, 
  ShapeCategoryType,
  PBRTextureSet 
} from './shapeSpecificTextures';
import { 
  applyFractalUVsToGeometry, 
  UVMappingMode 
} from './fractalUVMapping';
import { IndustrialExportManager } from './industrialExportStandards';
import { 
  createParametricDataForExport, 
  embedParametricDataInGLTF,
  ParametricDataPackage 
} from './parametricDataPreservation';

export type SketchfabTransparencyMode = 'opaque' | 'alpha_mask' | 'blending' | 'dithered' | 'additive' | 'refraction';

export interface SketchfabMaterialSettings {
  transparencyMode: SketchfabTransparencyMode;
  alphaThreshold: number;
  invertAlpha: boolean;
  tintColor: THREE.Color;
  indexOfRefraction: number;
  refractionRoughness: number;
  useNormalOffset: boolean;
}

export interface SketchfabExportOptions {
  filename: string;
  textureResolution: 1024 | 2048 | 4096 | 8192;
  uvMappingMode: UVMappingMode;
  uvScale: number;
  materialSettings: Partial<SketchfabMaterialSettings>;
  bakeLighting: boolean;
  exportSeparateTextures: boolean;
  includeAnimation: boolean;
  animationDuration: number;
  quality: 'standard' | 'high' | 'ultra';
  attribution: boolean;
}

export interface TextureExportResult {
  name: string;
  dataUrl: string;
  width: number;
  height: number;
  type: 'albedo' | 'normal' | 'roughness' | 'metallic' | 'ao' | 'opacity';
}

export interface SketchfabExportResult {
  success: boolean;
  glbBlob?: Blob;
  textures?: TextureExportResult[];
  metadata: SketchfabMetadata;
  attribution: string;
  error?: string;
}

export interface SketchfabMetadata {
  name: string;
  category: string;
  vertexCount: number;
  faceCount: number;
  textureResolution: number;
  transparencyMode: SketchfabTransparencyMode;
  uvMappingMode: UVMappingMode;
  hasNormalMap: boolean;
  hasPBRMaterials: boolean;
  exportDate: string;
  generator: string;
}

const DEFAULT_SKETCHFAB_OPTIONS: SketchfabExportOptions = {
  filename: 'dimension_shape',
  textureResolution: 2048,
  uvMappingMode: 'spherical',
  uvScale: 1,
  materialSettings: {
    transparencyMode: 'opaque',
    alphaThreshold: 0.5,
    invertAlpha: false,
    tintColor: new THREE.Color(0xffffff),
    indexOfRefraction: 1.45,
    refractionRoughness: 0.1,
    useNormalOffset: false
  },
  bakeLighting: false,
  exportSeparateTextures: true,
  includeAnimation: false,
  animationDuration: 4,
  quality: 'high',
  attribution: true
};

const TEXTURE_ATTRIBUTIONS = {
  procedural: 'Procedurally generated by Δmension Mathematical Universe',
  cc0: [
    'Textures may include CC0 licensed materials from:',
    '- ambientCG (https://ambientcg.com) - CC0 1.0',
    '- Poly Haven (https://polyhaven.com) - CC0 1.0',
    '- cgbookcase.com - CC0 1.0',
    'All procedural patterns are original mathematical derivations.'
  ].join('\n')
};

export class SketchfabExporter {
  private geometry: THREE.BufferGeometry;
  private material: THREE.Material;
  private shapeId: string;
  private shapeCategory: ShapeCategoryType;
  private shapeParameters: Record<string, number>;
  private industrialManager: IndustrialExportManager;
  private pbrTextures: PBRTextureSet | null = null;
  private opacityMap: THREE.Texture | null = null;

  constructor(
    geometry: THREE.BufferGeometry,
    material: THREE.Material,
    shapeId: string,
    shapeParameters: Record<string, number> = {}
  ) {
    this.geometry = geometry.clone();
    this.material = material;
    this.shapeId = shapeId;
    this.shapeCategory = getCategoryFromShapeId(shapeId);
    this.shapeParameters = shapeParameters;
    this.industrialManager = new IndustrialExportManager(this.geometry);
    
    if (!this.geometry.attributes.normal) {
      this.geometry.computeVertexNormals();
    }
  }

  async exportForSketchfab(
    options: Partial<SketchfabExportOptions> = {}
  ): Promise<SketchfabExportResult> {
    const opts = this.mergeOptions(options);
    
    try {
      console.log(`🎨 Starting Sketchfab export: ${opts.filename}`);
      console.log(`📐 Resolution: ${opts.textureResolution}px, UV Mode: ${opts.uvMappingMode}`);
      console.log(`🔍 Transparency: ${opts.materialSettings.transparencyMode}`);
      
      const enhancedGeometry = this.prepareGeometry(opts);
      const pbrMaterial = await this.createSketchfabMaterial(opts);
      const scene = this.buildExportScene(enhancedGeometry, pbrMaterial, opts);
      
      this.geometry.computeBoundingBox();
      const parametricPackage = createParametricDataForExport(
        this.shapeId,
        this.shapeParameters as any,
        {
          vertexCount: enhancedGeometry.attributes.position?.count || 0,
          faceCount: enhancedGeometry.index ? enhancedGeometry.index.count / 3 : 0,
          boundingBox: this.geometry.boundingBox
        },
        {
          sketchfabSettings: {
            transparencyMode: opts.materialSettings.transparencyMode,
            uvMappingMode: opts.uvMappingMode,
            textureResolution: opts.textureResolution,
            quality: opts.quality
          }
        }
      );
      console.log(`📦 Parametric data package created for Sketchfab: ${this.shapeId}`);
      
      const glbBlob = await this.exportToGLB(scene, opts, parametricPackage);
      
      let textures: TextureExportResult[] | undefined;
      if (opts.exportSeparateTextures) {
        textures = await this.exportTexturesAsPNG(opts);
      }
      
      const metadata = this.generateMetadata(enhancedGeometry, opts);
      const attribution = this.generateAttribution(opts);
      
      console.log(`✅ Sketchfab export complete with parametric data: ${opts.filename}`);
      
      return {
        success: true,
        glbBlob,
        textures,
        metadata,
        attribution
      };
    } catch (error) {
      console.error('❌ Sketchfab export failed:', error);
      return {
        success: false,
        metadata: this.generateMetadata(this.geometry, opts),
        attribution: '',
        error: error instanceof Error ? error.message : 'Unknown export error'
      };
    }
  }

  private mergeOptions(options: Partial<SketchfabExportOptions>): SketchfabExportOptions {
    return {
      ...DEFAULT_SKETCHFAB_OPTIONS,
      ...options,
      materialSettings: {
        ...DEFAULT_SKETCHFAB_OPTIONS.materialSettings,
        ...options.materialSettings
      }
    };
  }

  private prepareGeometry(opts: SketchfabExportOptions): THREE.BufferGeometry {
    const enhanced = this.geometry.clone();
    
    if (!enhanced.attributes.normal) {
      enhanced.computeVertexNormals();
    }
    
    applyFractalUVsToGeometry(enhanced, {
      mode: opts.uvMappingMode,
      scale: opts.uvScale,
      seamless: true,
      fractalIterations: opts.quality === 'ultra' ? 12 : opts.quality === 'high' ? 8 : 4
    });
    
    if (!enhanced.attributes.uv2) {
      const uv = enhanced.attributes.uv;
      if (uv) {
        enhanced.setAttribute('uv2', uv.clone());
      }
    }
    
    try {
      enhanced.computeTangents();
    } catch (e) {
      console.warn('Tangent computation skipped (non-indexed geometry)');
    }
    
    enhanced.computeBoundingBox();
    enhanced.computeBoundingSphere();
    
    return enhanced;
  }

  private async createSketchfabMaterial(
    opts: SketchfabExportOptions
  ): Promise<THREE.MeshStandardMaterial | THREE.MeshPhysicalMaterial> {
    this.pbrTextures = generateShapeSpecificPBRTextures({
      shapeId: this.shapeId,
      category: this.shapeCategory,
      parameters: this.shapeParameters,
      resolution: opts.textureResolution
    });
    
    const matSettings = opts.materialSettings;
    const isTransparent = matSettings.transparencyMode !== 'opaque';
    
    const baseMaterialProps: THREE.MeshStandardMaterialParameters = {
      color: this.getBaseColor(),
      metalness: this.getMetalness(),
      roughness: this.getRoughness(),
      map: this.pbrTextures.albedoMap,
      normalMap: this.pbrTextures.normalMap,
      normalScale: new THREE.Vector2(1.0, 1.0),
      roughnessMap: this.pbrTextures.roughnessMap,
      metalnessMap: this.pbrTextures.metallicMap,
      aoMap: this.pbrTextures.aoMap,
      aoMapIntensity: 0.8,
      side: THREE.DoubleSide,
      transparent: isTransparent,
      alphaTest: matSettings.transparencyMode === 'alpha_mask' ? matSettings.alphaThreshold : 0,
      depthWrite: matSettings.transparencyMode !== 'blending'
    };
    
    if (matSettings.transparencyMode === 'alpha_mask' || 
        matSettings.transparencyMode === 'blending' ||
        matSettings.transparencyMode === 'dithered') {
      this.opacityMap = this.generateOpacityMap(opts.textureResolution);
      baseMaterialProps.alphaMap = this.opacityMap;
      baseMaterialProps.transparent = true;
    }
    
    if (matSettings.transparencyMode === 'refraction') {
      const physicalMat = new THREE.MeshPhysicalMaterial({
        ...baseMaterialProps,
        transmission: 0.9,
        thickness: 0.5,
        ior: matSettings.indexOfRefraction || 1.45,
        roughness: matSettings.refractionRoughness || 0.1,
        envMapIntensity: 1.0,
        clearcoat: 0.3,
        clearcoatRoughness: 0.1
      });
      
      return physicalMat;
    }
    
    return new THREE.MeshStandardMaterial(baseMaterialProps);
  }

  private generateOpacityMap(resolution: number): THREE.Texture {
    const canvas = document.createElement('canvas');
    canvas.width = resolution;
    canvas.height = resolution;
    const ctx = canvas.getContext('2d')!;
    
    const gradient = ctx.createRadialGradient(
      resolution / 2, resolution / 2, 0,
      resolution / 2, resolution / 2, resolution / 2
    );
    gradient.addColorStop(0, 'rgba(255, 255, 255, 1)');
    gradient.addColorStop(0.7, 'rgba(255, 255, 255, 0.8)');
    gradient.addColorStop(1, 'rgba(255, 255, 255, 0.2)');
    
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, resolution, resolution);
    
    const texture = new THREE.CanvasTexture(canvas);
    texture.wrapS = THREE.RepeatWrapping;
    texture.wrapT = THREE.RepeatWrapping;
    texture.colorSpace = THREE.LinearSRGBColorSpace;
    
    return texture;
  }

  private buildExportScene(
    geometry: THREE.BufferGeometry,
    material: THREE.Material,
    opts: SketchfabExportOptions
  ): THREE.Scene {
    const scene = new THREE.Scene();
    scene.background = null;
    
    const mesh = new THREE.Mesh(geometry, material);
    mesh.name = opts.filename;
    mesh.castShadow = true;
    mesh.receiveShadow = true;
    
    mesh.userData = {
      sketchfab: {
        materialSettings: opts.materialSettings,
        transparencyMode: opts.materialSettings.transparencyMode,
        category: this.shapeCategory,
        shapeId: this.shapeId
      }
    };
    
    scene.add(mesh);
    
    if (opts.bakeLighting) {
      const ambientLight = new THREE.AmbientLight(0xffffff, 0.4);
      scene.add(ambientLight);
      
      const keyLight = new THREE.DirectionalLight(0xffffff, 1.0);
      keyLight.position.set(5, 10, 7);
      keyLight.castShadow = true;
      scene.add(keyLight);
      
      const fillLight = new THREE.DirectionalLight(0x8888ff, 0.3);
      fillLight.position.set(-5, 3, -5);
      scene.add(fillLight);
      
      const rimLight = new THREE.DirectionalLight(0xffaa44, 0.2);
      rimLight.position.set(0, -5, -10);
      scene.add(rimLight);
    }
    
    return scene;
  }

  private async exportToGLB(
    scene: THREE.Scene,
    opts: SketchfabExportOptions,
    parametricPackage?: ParametricDataPackage
  ): Promise<Blob> {
    const exporter = new GLTFExporter();
    
    if (parametricPackage) {
      scene.userData = {
        ...scene.userData,
        parametricData: parametricPackage
      };
      console.log(`📦 Parametric data attached to scene for GLB export`);
    }
    
    return new Promise((resolve, reject) => {
      exporter.parse(
        scene,
        (result) => {
          const blob = new Blob([result as ArrayBuffer], { type: 'model/gltf-binary' });
          console.log(`📦 GLB exported with parametric data embedded`);
          resolve(blob);
        },
        (error) => {
          reject(error);
        },
        {
          binary: true,
          embedImages: true,
          maxTextureSize: opts.textureResolution,
          includeCustomExtensions: true
        }
      );
    });
  }

  private async exportTexturesAsPNG(
    opts: SketchfabExportOptions
  ): Promise<TextureExportResult[]> {
    const textures: TextureExportResult[] = [];
    const resolution = opts.textureResolution;
    
    if (!this.pbrTextures) {
      this.pbrTextures = generateShapeSpecificPBRTextures({
        shapeId: this.shapeId,
        category: this.shapeCategory,
        parameters: this.shapeParameters,
        resolution
      });
    }
    
    const textureMap: [keyof PBRTextureSet, TextureExportResult['type']][] = [
      ['albedoMap', 'albedo'],
      ['normalMap', 'normal'],
      ['roughnessMap', 'roughness'],
      ['metallicMap', 'metallic'],
      ['aoMap', 'ao']
    ];
    
    for (const [key, type] of textureMap) {
      const texture = this.pbrTextures[key];
      if (texture && texture.image) {
        const dataUrl = this.textureToDataURL(texture, resolution);
        textures.push({
          name: `${opts.filename}_${type}.png`,
          dataUrl,
          width: resolution,
          height: resolution,
          type
        });
      }
    }
    
    if (this.opacityMap) {
      const dataUrl = this.textureToDataURL(this.opacityMap, resolution);
      textures.push({
        name: `${opts.filename}_opacity.png`,
        dataUrl,
        width: resolution,
        height: resolution,
        type: 'opacity'
      });
    }
    
    return textures;
  }

  private textureToDataURL(texture: THREE.Texture, resolution: number): string {
    const canvas = document.createElement('canvas');
    canvas.width = resolution;
    canvas.height = resolution;
    const ctx = canvas.getContext('2d')!;
    
    if (texture.image instanceof HTMLCanvasElement) {
      ctx.drawImage(texture.image, 0, 0, resolution, resolution);
    } else if (texture.image instanceof HTMLImageElement) {
      ctx.drawImage(texture.image, 0, 0, resolution, resolution);
    } else {
      ctx.fillStyle = '#808080';
      ctx.fillRect(0, 0, resolution, resolution);
    }
    
    return canvas.toDataURL('image/png');
  }

  private generateMetadata(
    geometry: THREE.BufferGeometry,
    opts: SketchfabExportOptions
  ): SketchfabMetadata {
    const positionAttr = geometry.attributes.position;
    const vertexCount = positionAttr.count;
    const indexAttr = geometry.index;
    const faceCount = indexAttr ? indexAttr.count / 3 : vertexCount / 3;
    
    return {
      name: opts.filename,
      category: this.shapeCategory,
      vertexCount,
      faceCount: Math.floor(faceCount),
      textureResolution: opts.textureResolution,
      transparencyMode: opts.materialSettings.transparencyMode || 'opaque',
      uvMappingMode: opts.uvMappingMode,
      hasNormalMap: true,
      hasPBRMaterials: true,
      exportDate: new Date().toISOString(),
      generator: 'Δmension Mathematical Universe v2.0'
    };
  }

  private generateAttribution(opts: SketchfabExportOptions): string {
    if (!opts.attribution) return '';
    
    return [
      '═══════════════════════════════════════════════════════════',
      '  Δmension Mathematical Universe - Export Attribution',
      '═══════════════════════════════════════════════════════════',
      '',
      `  Shape: ${this.shapeId}`,
      `  Category: ${this.shapeCategory}`,
      `  Export Date: ${new Date().toISOString()}`,
      '',
      '  TEXTURE ATTRIBUTION:',
      '  ' + TEXTURE_ATTRIBUTIONS.procedural,
      '',
      TEXTURE_ATTRIBUTIONS.cc0,
      '',
      '  LICENSE:',
      '  Mathematical visualizations © UUON Foundation Inc.',
      '  Procedural textures are generated and may be used freely.',
      '',
      '═══════════════════════════════════════════════════════════'
    ].join('\n');
  }

  private getBaseColor(): THREE.Color {
    if (this.material instanceof THREE.MeshStandardMaterial) {
      return this.material.color.clone();
    }
    return new THREE.Color(0x00ff88);
  }

  private getMetalness(): number {
    if (this.material instanceof THREE.MeshStandardMaterial) {
      return this.material.metalness;
    }
    return 0.3;
  }

  private getRoughness(): number {
    if (this.material instanceof THREE.MeshStandardMaterial) {
      return this.material.roughness;
    }
    return 0.4;
  }

  downloadGLB(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}.glb`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  downloadTextures(textures: TextureExportResult[]): void {
    textures.forEach((tex, index) => {
      setTimeout(() => {
        const link = document.createElement('a');
        link.href = tex.dataUrl;
        link.download = tex.name;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      }, index * 200);
    });
  }

  downloadAll(result: SketchfabExportResult, filename: string): void {
    if (result.glbBlob) {
      this.downloadGLB(result.glbBlob, filename);
    }
    
    if (result.textures) {
      setTimeout(() => {
        this.downloadTextures(result.textures!);
      }, 500);
    }
    
    if (result.attribution) {
      setTimeout(() => {
        const blob = new Blob([result.attribution], { type: 'text/plain' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = `${filename}_attribution.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      }, 1000 + (result.textures?.length || 0) * 200);
    }
  }

  downloadTexturesAsZip(textures: TextureExportResult[], filename: string): void {
    console.log(`📦 Packaging ${textures.length} textures for download...`);
    textures.forEach((tex, index) => {
      setTimeout(() => {
        const link = document.createElement('a');
        link.href = tex.dataUrl;
        link.download = tex.name;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        console.log(`✅ Downloaded: ${tex.name}`);
      }, index * 300);
    });
  }
}

export async function exportShapeForSketchfab(
  mesh: THREE.Mesh,
  shapeId: string,
  shapeParameters: Record<string, number>,
  options: Partial<SketchfabExportOptions> = {}
): Promise<SketchfabExportResult> {
  const exporter = new SketchfabExporter(
    mesh.geometry,
    mesh.material as THREE.Material,
    shapeId,
    shapeParameters
  );
  
  return exporter.exportForSketchfab(options);
}

export function getSketchfabTransparencyModes(): { value: SketchfabTransparencyMode; label: string; description: string }[] {
  return [
    { 
      value: 'opaque', 
      label: 'Opaque', 
      description: 'Solid material with no transparency' 
    },
    { 
      value: 'alpha_mask', 
      label: 'Alpha Mask', 
      description: 'Binary cutout transparency (fastest)' 
    },
    { 
      value: 'blending', 
      label: 'Blending', 
      description: 'Smooth transparency with depth sorting' 
    },
    { 
      value: 'dithered', 
      label: 'Dithered', 
      description: 'Fast transparency with noise pattern' 
    },
    { 
      value: 'additive', 
      label: 'Additive', 
      description: 'Glowing/emissive transparency' 
    },
    { 
      value: 'refraction', 
      label: 'Refraction', 
      description: 'Glass-like with light bending (slowest)' 
    }
  ];
}
