/**
 * UNIVERSAL LEXICON ENGINE
 * A comprehensive semantic engine for extracting, expanding, and mapping
 * all mathematical terms, formulas, and concepts in Dmension Mathematical Universe.
 * 
 * Capabilities:
 * - Term extraction from shape libraries
 * - Definition and synonym expansion
 * - Multilingual translations (EN, ES, DE, FR, ZH)
 * - Formula-to-code conversion (JS, Python, TS, C++, Rust)
 * - Ontological relationship mapping
 * - SEO metadata generation
 */

export interface LexiconEntry {
  id: string;
  term: string;
  type: 'term' | 'phrase' | 'formula' | 'concept' | 'symbol' | 'shape';
  definition: string;
  synonyms: string[];
  antonyms: string[];
  rootWord: string;
  relatedTerms: string[];
  category: string;
  subcategory: string;
  seoTags: string[];
  translations: {
    en: string;
    es: string;
    de: string;
    fr: string;
    zh: string;
  };
  formula?: {
    latex: string;
    variables: string[];
    description: string;
  };
  codeImplementations?: {
    javascript: string;
    python: string;
    typescript: string;
    cpp: string;
    rust: string;
  };
  semanticRelations: {
    parent?: string;
    children: string[];
    siblings: string[];
  };
  metadata: {
    createdAt: string;
    source: string;
    confidence: number;
  };
}

export interface TaxonomyNode {
  term: string;
  children: TaxonomyNode[];
  level: number;
}

export interface FormulaEntry {
  id: string;
  name: string;
  latex: string;
  description: string;
  variables: Array<{
    symbol: string;
    meaning: string;
    range?: string;
  }>;
  implementations: {
    javascript: string;
    python: string;
    typescript: string;
    cpp: string;
    rust: string;
  };
  category: string;
  relatedShapes: string[];
}

const MATHEMATICAL_TERMS_DATABASE: Record<string, Partial<LexiconEntry>> = {
  sphere: {
    definition: "A perfectly round three-dimensional shape where every point on its surface is equidistant from its center",
    synonyms: ["ball", "globe", "orb", "spheroid"],
    antonyms: ["cube", "polyhedron", "angular shape"],
    rootWord: "Latin 'sphaera', Greek 'sphaira' meaning ball",
    translations: {
      en: "sphere",
      es: "esfera",
      de: "Kugel",
      fr: "sphère",
      zh: "球体"
    },
    seoTags: ["3D sphere", "parametric sphere", "sphere geometry", "spherical surface"]
  },
  torus: {
    definition: "A donut-shaped surface of revolution generated by revolving a circle about an axis coplanar with the circle",
    synonyms: ["donut", "ring", "toroid", "anchor ring"],
    antonyms: ["sphere", "plane"],
    rootWord: "Latin 'torus' meaning swelling, cushion",
    translations: {
      en: "torus",
      es: "toro",
      de: "Torus",
      fr: "tore",
      zh: "环面"
    },
    seoTags: ["torus geometry", "donut shape", "parametric torus", "toroidal surface"]
  },
  klein_bottle: {
    definition: "A non-orientable surface with no distinct inside or outside, a four-dimensional analog of a Möbius strip",
    synonyms: ["Klein surface", "non-orientable manifold"],
    antonyms: ["orientable surface", "sphere"],
    rootWord: "Named after Felix Klein, German mathematician",
    translations: {
      en: "Klein bottle",
      es: "botella de Klein",
      de: "Kleinsche Flasche",
      fr: "bouteille de Klein",
      zh: "克莱因瓶"
    },
    seoTags: ["Klein bottle", "non-orientable", "4D geometry", "topological surface"]
  },
  mobius_strip: {
    definition: "A one-sided non-orientable surface with only one boundary curve, created by giving a strip a half-twist and joining the ends",
    synonyms: ["Möbius band", "twisted loop", "one-sided surface"],
    antonyms: ["cylinder", "orientable surface"],
    rootWord: "Named after August Ferdinand Möbius, German mathematician",
    translations: {
      en: "Möbius strip",
      es: "cinta de Möbius",
      de: "Möbiusband",
      fr: "ruban de Möbius",
      zh: "莫比乌斯带"
    },
    seoTags: ["Mobius strip", "topology", "one-sided surface", "non-orientable"]
  },
  helix: {
    definition: "A three-dimensional curve that spirals around an axis while advancing along it, like a spring or DNA strand",
    synonyms: ["spiral", "coil", "corkscrew", "helical curve"],
    antonyms: ["straight line", "circle"],
    rootWord: "Greek 'helix' meaning spiral, winding",
    translations: {
      en: "helix",
      es: "hélice",
      de: "Helix",
      fr: "hélice",
      zh: "螺旋"
    },
    seoTags: ["helix curve", "spiral geometry", "3D helix", "helical shape"]
  },
  catenoid: {
    definition: "A minimal surface formed by rotating a catenary curve about its directrix, shaped like two connected funnels",
    synonyms: ["catenary surface", "minimal surface of revolution"],
    antonyms: ["maximal surface"],
    rootWord: "Latin 'catena' meaning chain",
    translations: {
      en: "catenoid",
      es: "catenoide",
      de: "Katenoid",
      fr: "caténoïde",
      zh: "悬链面"
    },
    seoTags: ["catenoid", "minimal surface", "soap film", "catenary"]
  },
  helicoid: {
    definition: "A ruled surface formed by moving a straight line along a helical path, the only minimal surface besides the plane that is also ruled",
    synonyms: ["helical surface", "spiral ramp"],
    antonyms: ["plane"],
    rootWord: "Greek 'helix' + 'eidos' meaning spiral form",
    translations: {
      en: "helicoid",
      es: "helicoide",
      de: "Helikoid",
      fr: "hélicoïde",
      zh: "螺旋面"
    },
    seoTags: ["helicoid", "ruled surface", "minimal surface", "helical geometry"]
  },
  hyperbolic_paraboloid: {
    definition: "A doubly-ruled saddle-shaped surface with negative Gaussian curvature, commonly seen in architecture (Pringles chip shape)",
    synonyms: ["saddle surface", "hypar", "anticlastic surface"],
    antonyms: ["sphere", "ellipsoid"],
    rootWord: "Greek 'hyperbole' + 'parabola'",
    translations: {
      en: "hyperbolic paraboloid",
      es: "paraboloide hiperbólico",
      de: "hyperbolisches Paraboloid",
      fr: "paraboloïde hyperbolique",
      zh: "双曲抛物面"
    },
    seoTags: ["hyperbolic paraboloid", "saddle shape", "architectural geometry", "doubly ruled"]
  },
  tesseract: {
    definition: "A four-dimensional hypercube, the 4D analog of a cube, consisting of 8 cubic cells",
    synonyms: ["hypercube", "4-cube", "8-cell", "octachoron"],
    antonyms: ["cube", "3D shape"],
    rootWord: "Greek 'tessares' meaning four + 'aktis' meaning ray",
    translations: {
      en: "tesseract",
      es: "teseracto",
      de: "Tesserakt",
      fr: "tesseract",
      zh: "超立方体"
    },
    seoTags: ["tesseract", "hypercube", "4D geometry", "fourth dimension"]
  },
  fibonacci_spiral: {
    definition: "A logarithmic spiral whose growth factor is related to the golden ratio φ, approximated by quarter-circle arcs in Fibonacci squares",
    synonyms: ["golden spiral", "phi spiral", "logarithmic spiral"],
    antonyms: ["linear progression"],
    rootWord: "Named after Leonardo Fibonacci, Italian mathematician",
    translations: {
      en: "Fibonacci spiral",
      es: "espiral de Fibonacci",
      de: "Fibonacci-Spirale",
      fr: "spirale de Fibonacci",
      zh: "斐波那契螺旋"
    },
    seoTags: ["Fibonacci", "golden ratio", "spiral", "phi", "nature patterns"]
  },
  calabi_yau: {
    definition: "A complex manifold with Ricci-flat Kähler metric, crucial in string theory for compactifying extra dimensions",
    synonyms: ["Calabi-Yau manifold", "CY manifold", "string theory manifold"],
    antonyms: [],
    rootWord: "Named after Eugenio Calabi and Shing-Tung Yau",
    translations: {
      en: "Calabi-Yau manifold",
      es: "variedad de Calabi-Yau",
      de: "Calabi-Yau-Mannigfaltigkeit",
      fr: "variété de Calabi-Yau",
      zh: "卡拉比-丘流形"
    },
    seoTags: ["Calabi-Yau", "string theory", "extra dimensions", "theoretical physics"]
  },
  mandelbrot: {
    definition: "The set of complex numbers c for which the iteration z(n+1) = z(n)² + c does not diverge to infinity",
    synonyms: ["Mandelbrot set", "M-set", "fractal set"],
    antonyms: [],
    rootWord: "Named after Benoît Mandelbrot, mathematician",
    translations: {
      en: "Mandelbrot set",
      es: "conjunto de Mandelbrot",
      de: "Mandelbrot-Menge",
      fr: "ensemble de Mandelbrot",
      zh: "曼德博集合"
    },
    seoTags: ["Mandelbrot", "fractal", "complex dynamics", "chaos theory"]
  },
  golden_ratio: {
    definition: "The mathematical ratio φ ≈ 1.618034, where (a+b)/a = a/b, found throughout nature, art, and architecture",
    synonyms: ["phi", "divine proportion", "golden mean", "golden section"],
    antonyms: [],
    rootWord: "Greek 'chrysos' meaning gold + Latin 'ratio'",
    translations: {
      en: "golden ratio",
      es: "proporción áurea",
      de: "Goldener Schnitt",
      fr: "nombre d'or",
      zh: "黄金比例"
    },
    seoTags: ["golden ratio", "phi", "Fibonacci", "sacred geometry", "divine proportion"]
  },
  quaternion: {
    definition: "A four-dimensional number system extending complex numbers, used for 3D rotations without gimbal lock",
    synonyms: ["Hamilton numbers", "hypercomplex number"],
    antonyms: ["real number", "complex number"],
    rootWord: "Latin 'quaternio' meaning group of four",
    translations: {
      en: "quaternion",
      es: "cuaternión",
      de: "Quaternion",
      fr: "quaternion",
      zh: "四元数"
    },
    seoTags: ["quaternion", "3D rotation", "hypercomplex", "Hamilton"]
  },
  enneper_surface: {
    definition: "A self-intersecting minimal surface with algebraic polynomial parametrization, discovered by Alfred Enneper",
    synonyms: ["Enneper minimal surface"],
    antonyms: [],
    rootWord: "Named after Alfred Enneper, German mathematician",
    translations: {
      en: "Enneper surface",
      es: "superficie de Enneper",
      de: "Enneper-Fläche",
      fr: "surface d'Enneper",
      zh: "恩内珀曲面"
    },
    seoTags: ["Enneper", "minimal surface", "self-intersecting", "algebraic surface"]
  }
};

const FORMULA_DATABASE: Record<string, FormulaEntry> = {
  sphere_parametric: {
    id: "sphere_parametric",
    name: "Sphere Parametric Equations",
    latex: "x = r\\sin(\\phi)\\cos(\\theta), \\quad y = r\\sin(\\phi)\\sin(\\theta), \\quad z = r\\cos(\\phi)",
    description: "Parametric equations for a sphere of radius r using spherical coordinates",
    variables: [
      { symbol: "r", meaning: "radius of the sphere", range: "r > 0" },
      { symbol: "φ", meaning: "polar angle (latitude)", range: "[0, π]" },
      { symbol: "θ", meaning: "azimuthal angle (longitude)", range: "[0, 2π]" }
    ],
    implementations: {
      javascript: `function sphere(u, v, r = 1) {
  const phi = u * Math.PI;
  const theta = v * 2 * Math.PI;
  return [
    r * Math.sin(phi) * Math.cos(theta),
    r * Math.sin(phi) * Math.sin(theta),
    r * Math.cos(phi)
  ];
}`,
      python: `def sphere(u: float, v: float, r: float = 1.0) -> tuple:
    phi = u * math.pi
    theta = v * 2 * math.pi
    return (
        r * math.sin(phi) * math.cos(theta),
        r * math.sin(phi) * math.sin(theta),
        r * math.cos(phi)
    )`,
      typescript: `function sphere(u: number, v: number, r: number = 1): [number, number, number] {
  const phi = u * Math.PI;
  const theta = v * 2 * Math.PI;
  return [
    r * Math.sin(phi) * Math.cos(theta),
    r * Math.sin(phi) * Math.sin(theta),
    r * Math.cos(phi)
  ];
}`,
      cpp: `std::tuple<double, double, double> sphere(double u, double v, double r = 1.0) {
    double phi = u * M_PI;
    double theta = v * 2 * M_PI;
    return {
        r * sin(phi) * cos(theta),
        r * sin(phi) * sin(theta),
        r * cos(phi)
    };
}`,
      rust: `fn sphere(u: f64, v: f64, r: f64) -> (f64, f64, f64) {
    let phi = u * std::f64::consts::PI;
    let theta = v * 2.0 * std::f64::consts::PI;
    (
        r * phi.sin() * theta.cos(),
        r * phi.sin() * theta.sin(),
        r * phi.cos()
    )
}`
    },
    category: "basic_shapes",
    relatedShapes: ["sphere", "ellipsoid", "ovoid"]
  },
  torus_parametric: {
    id: "torus_parametric",
    name: "Torus Parametric Equations",
    latex: "x = (R + r\\cos(v))\\cos(u), \\quad y = (R + r\\cos(v))\\sin(u), \\quad z = r\\sin(v)",
    description: "Parametric equations for a torus with major radius R and minor radius r",
    variables: [
      { symbol: "R", meaning: "major radius (center to tube center)", range: "R > r" },
      { symbol: "r", meaning: "minor radius (tube radius)", range: "r > 0" },
      { symbol: "u", meaning: "angle around the tube", range: "[0, 2π]" },
      { symbol: "v", meaning: "angle around the torus", range: "[0, 2π]" }
    ],
    implementations: {
      javascript: `function torus(u, v, R = 2, r = 0.5) {
  const theta = u * 2 * Math.PI;
  const phi = v * 2 * Math.PI;
  return [
    (R + r * Math.cos(phi)) * Math.cos(theta),
    (R + r * Math.cos(phi)) * Math.sin(theta),
    r * Math.sin(phi)
  ];
}`,
      python: `def torus(u: float, v: float, R: float = 2.0, r: float = 0.5) -> tuple:
    theta = u * 2 * math.pi
    phi = v * 2 * math.pi
    return (
        (R + r * math.cos(phi)) * math.cos(theta),
        (R + r * math.cos(phi)) * math.sin(theta),
        r * math.sin(phi)
    )`,
      typescript: `function torus(u: number, v: number, R: number = 2, r: number = 0.5): [number, number, number] {
  const theta = u * 2 * Math.PI;
  const phi = v * 2 * Math.PI;
  return [
    (R + r * Math.cos(phi)) * Math.cos(theta),
    (R + r * Math.cos(phi)) * Math.sin(theta),
    r * Math.sin(phi)
  ];
}`,
      cpp: `std::tuple<double, double, double> torus(double u, double v, double R = 2.0, double r = 0.5) {
    double theta = u * 2 * M_PI;
    double phi = v * 2 * M_PI;
    return {
        (R + r * cos(phi)) * cos(theta),
        (R + r * cos(phi)) * sin(theta),
        r * sin(phi)
    };
}`,
      rust: `fn torus(u: f64, v: f64, r_major: f64, r_minor: f64) -> (f64, f64, f64) {
    let theta = u * 2.0 * std::f64::consts::PI;
    let phi = v * 2.0 * std::f64::consts::PI;
    (
        (r_major + r_minor * phi.cos()) * theta.cos(),
        (r_major + r_minor * phi.cos()) * theta.sin(),
        r_minor * phi.sin()
    )
}`
    },
    category: "basic_shapes",
    relatedShapes: ["torus", "clifford_torus", "horn_torus"]
  },
  klein_bottle_parametric: {
    id: "klein_bottle_parametric",
    name: "Klein Bottle Parametric Equations",
    latex: "\\text{Figure-8 immersion in } \\mathbb{R}^3",
    description: "Parametric equations for a Klein bottle immersion in 3D space",
    variables: [
      { symbol: "u", meaning: "parameter along the bottle", range: "[0, 2π]" },
      { symbol: "v", meaning: "parameter around the cross-section", range: "[0, 2π]" },
      { symbol: "r", meaning: "radius scaling factor", range: "r > 0" }
    ],
    implementations: {
      javascript: `function kleinBottle(u, v, r = 1) {
  const halfU = u / 2;
  const cosU = Math.cos(u), sinU = Math.sin(u);
  const cosV = Math.cos(v), sinV = Math.sin(v);
  const cos2U = Math.cos(2 * u);
  
  const x = r * (cosU * (1 + sinU) + sinV * (1 - cosU / 2));
  const y = r * sinU + cosV * (1 - cosU / 2);
  const z = r * Math.sin(halfU) * sinV;
  
  return [x, y, z];
}`,
      python: `def klein_bottle(u: float, v: float, r: float = 1.0) -> tuple:
    half_u = u / 2
    cos_u, sin_u = math.cos(u), math.sin(u)
    cos_v, sin_v = math.cos(v), math.sin(v)
    
    x = r * (cos_u * (1 + sin_u) + sin_v * (1 - cos_u / 2))
    y = r * sin_u + cos_v * (1 - cos_u / 2)
    z = r * math.sin(half_u) * sin_v
    
    return (x, y, z)`,
      typescript: `function kleinBottle(u: number, v: number, r: number = 1): [number, number, number] {
  const halfU = u / 2;
  const cosU = Math.cos(u), sinU = Math.sin(u);
  const cosV = Math.cos(v), sinV = Math.sin(v);
  
  const x = r * (cosU * (1 + sinU) + sinV * (1 - cosU / 2));
  const y = r * sinU + cosV * (1 - cosU / 2);
  const z = r * Math.sin(halfU) * sinV;
  
  return [x, y, z];
}`,
      cpp: `std::tuple<double, double, double> klein_bottle(double u, double v, double r = 1.0) {
    double half_u = u / 2;
    double cos_u = cos(u), sin_u = sin(u);
    double cos_v = cos(v), sin_v = sin(v);
    
    double x = r * (cos_u * (1 + sin_u) + sin_v * (1 - cos_u / 2));
    double y = r * sin_u + cos_v * (1 - cos_u / 2);
    double z = r * sin(half_u) * sin_v;
    
    return {x, y, z};
}`,
      rust: `fn klein_bottle(u: f64, v: f64, r: f64) -> (f64, f64, f64) {
    let half_u = u / 2.0;
    let (cos_u, sin_u) = (u.cos(), u.sin());
    let (cos_v, sin_v) = (v.cos(), v.sin());
    
    let x = r * (cos_u * (1.0 + sin_u) + sin_v * (1.0 - cos_u / 2.0));
    let y = r * sin_u + cos_v * (1.0 - cos_u / 2.0);
    let z = r * half_u.sin() * sin_v;
    
    (x, y, z)
}`
    },
    category: "topological_surfaces",
    relatedShapes: ["klein_bottle", "mobius_strip", "cross_cap"]
  }
};

const CATEGORY_TAXONOMY: TaxonomyNode = {
  term: "Mathematical Shapes",
  level: 0,
  children: [
    {
      term: "Basic Shapes",
      level: 1,
      children: [
        { term: "sphere", level: 2, children: [] },
        { term: "cube", level: 2, children: [] },
        { term: "cylinder", level: 2, children: [] },
        { term: "cone", level: 2, children: [] },
        { term: "torus", level: 2, children: [] }
      ]
    },
    {
      term: "Minimal Surfaces",
      level: 1,
      children: [
        { term: "catenoid", level: 2, children: [] },
        { term: "helicoid", level: 2, children: [] },
        { term: "enneper_surface", level: 2, children: [] },
        { term: "costa_surface", level: 2, children: [] }
      ]
    },
    {
      term: "Topological Surfaces",
      level: 1,
      children: [
        { term: "klein_bottle", level: 2, children: [] },
        { term: "mobius_strip", level: 2, children: [] },
        { term: "cross_cap", level: 2, children: [] },
        { term: "boy_surface", level: 2, children: [] }
      ]
    },
    {
      term: "Hyperdimensional",
      level: 1,
      children: [
        { term: "tesseract", level: 2, children: [] },
        { term: "120_cell", level: 2, children: [] },
        { term: "600_cell", level: 2, children: [] },
        { term: "calabi_yau", level: 2, children: [] }
      ]
    },
    {
      term: "Sacred Geometry",
      level: 1,
      children: [
        { term: "flower_of_life", level: 2, children: [] },
        { term: "metatrons_cube", level: 2, children: [] },
        { term: "sri_yantra", level: 2, children: [] },
        { term: "fibonacci_spiral", level: 2, children: [] }
      ]
    },
    {
      term: "Fractals",
      level: 1,
      children: [
        { term: "mandelbrot", level: 2, children: [] },
        { term: "julia_set", level: 2, children: [] },
        { term: "sierpinski", level: 2, children: [] },
        { term: "menger_sponge", level: 2, children: [] }
      ]
    },
    {
      term: "Physics Surfaces",
      level: 1,
      children: [
        { term: "schwarzschild", level: 2, children: [] },
        { term: "kerr_black_hole", level: 2, children: [] },
        { term: "gravitational_wave", level: 2, children: [] },
        { term: "higgs_field", level: 2, children: [] }
      ]
    },
    {
      term: "Biological Forms",
      level: 1,
      children: [
        { term: "dna_helix", level: 2, children: [] },
        { term: "protein_fold", level: 2, children: [] },
        { term: "cell_membrane", level: 2, children: [] },
        { term: "nautilus_shell", level: 2, children: [] }
      ]
    }
  ]
};

export class UniversalLexiconEngine {
  private entries: Map<string, LexiconEntry> = new Map();
  private formulas: Map<string, FormulaEntry> = new Map();
  private taxonomy: TaxonomyNode = CATEGORY_TAXONOMY;

  constructor() {
    this.initializeDatabase();
  }

  private initializeDatabase(): void {
    Object.entries(MATHEMATICAL_TERMS_DATABASE).forEach(([key, value]) => {
      const entry: LexiconEntry = {
        id: key,
        term: key.replace(/_/g, ' '),
        type: 'shape',
        definition: value.definition || '',
        synonyms: value.synonyms || [],
        antonyms: value.antonyms || [],
        rootWord: value.rootWord || '',
        relatedTerms: [],
        category: this.detectCategory(key),
        subcategory: '',
        seoTags: value.seoTags || [],
        translations: value.translations || { en: key, es: key, de: key, fr: key, zh: key },
        semanticRelations: { children: [], siblings: [] },
        metadata: {
          createdAt: new Date().toISOString(),
          source: 'Dmension Mathematical Universe',
          confidence: 0.95
        }
      };
      this.entries.set(key, entry);
    });

    Object.entries(FORMULA_DATABASE).forEach(([key, value]) => {
      this.formulas.set(key, value);
    });

    console.log(`📘 Lexicon Engine initialized: ${this.entries.size} terms, ${this.formulas.size} formulas`);
  }

  private detectCategory(term: string): string {
    const categoryPatterns: Record<string, string[]> = {
      'basic_shapes': ['sphere', 'cube', 'cylinder', 'cone', 'torus', 'plane'],
      'minimal_surfaces': ['catenoid', 'helicoid', 'enneper', 'costa', 'scherk'],
      'topological': ['klein', 'mobius', 'cross_cap', 'boy_surface'],
      'hyperdimensional': ['tesseract', '120_cell', '600_cell', 'calabi', 'hopf'],
      'sacred_geometry': ['flower', 'metatron', 'sri_yantra', 'fibonacci', 'golden'],
      'fractals': ['mandelbrot', 'julia', 'sierpinski', 'menger', 'cantor'],
      'physics': ['schwarzschild', 'kerr', 'gravitational', 'higgs', 'quantum'],
      'biological': ['dna', 'protein', 'cell', 'nautilus', 'neuron']
    };

    for (const [category, patterns] of Object.entries(categoryPatterns)) {
      if (patterns.some(p => term.toLowerCase().includes(p))) {
        return category;
      }
    }
    return 'general_mathematical';
  }

  extractTermsFromShapeName(shapeName: string): string[] {
    const words = shapeName
      .replace(/_/g, ' ')
      .replace(/([A-Z])/g, ' $1')
      .toLowerCase()
      .split(/\s+/)
      .filter(w => w.length > 2);
    return [...new Set(words)];
  }

  expandTerm(term: string): LexiconEntry | null {
    return this.entries.get(term) || null;
  }

  getFormulaImplementation(formulaId: string, language: keyof FormulaEntry['implementations']): string | null {
    const formula = this.formulas.get(formulaId);
    return formula?.implementations[language] || null;
  }

  getAllFormulas(): FormulaEntry[] {
    return Array.from(this.formulas.values());
  }

  getTaxonomy(): TaxonomyNode {
    return this.taxonomy;
  }

  searchTerms(query: string): LexiconEntry[] {
    const lowerQuery = query.toLowerCase();
    return Array.from(this.entries.values()).filter(entry =>
      entry.term.toLowerCase().includes(lowerQuery) ||
      entry.definition.toLowerCase().includes(lowerQuery) ||
      entry.synonyms.some(s => s.toLowerCase().includes(lowerQuery))
    );
  }

  generateSEOMetadata(term: string): { title: string; description: string; keywords: string[] } | null {
    const entry = this.entries.get(term);
    if (!entry) return null;

    return {
      title: `${entry.term.charAt(0).toUpperCase() + entry.term.slice(1)} - 3D Mathematical Visualization | Dmension`,
      description: entry.definition.substring(0, 160),
      keywords: [...entry.seoTags, ...entry.synonyms, entry.category]
    };
  }

  exportToJSON(): {
    lexicon: LexiconEntry[];
    formulas: FormulaEntry[];
    taxonomy: TaxonomyNode;
  } {
    return {
      lexicon: Array.from(this.entries.values()),
      formulas: Array.from(this.formulas.values()),
      taxonomy: this.taxonomy
    };
  }

  getStats(): {
    totalTerms: number;
    totalFormulas: number;
    categories: string[];
    languages: string[];
  } {
    const categories = [...new Set(Array.from(this.entries.values()).map(e => e.category))];
    return {
      totalTerms: this.entries.size,
      totalFormulas: this.formulas.size,
      categories,
      languages: ['en', 'es', 'de', 'fr', 'zh']
    };
  }
}

export const lexiconEngine = new UniversalLexiconEngine();
