import {createRequire} from 'module';
const require=createRequire(import.meta.url);
const solc=require('solc');
const {ethers}=require('ethers');
const RS=`pragma solidity ^0.8.20;contract UUONLevelRegistry{address public owner;address public uuonToken;struct Level{bool active;uint256 activatedAt;uint256 fibValue;string name;}mapping(uint8=>Level)public levels;event LevelActivated(uint8,uint256,string);constructor(address t){owner=msg.sender;uuonToken=t;levels[1]=Level(false,0,1,"UUON");levels[2]=Level(false,0,2,"PIEZ+PSENT");}modifier onlyOwner(){require(msg.sender==owner);_;}function activateLevel(uint8 l)external onlyOwner{levels[l].active=true;levels[l].activatedAt=block.timestamp;}function getLevel(uint8 l)external view returns(bool,uint256,uint256,string memory){Level memory v=levels[l];return(v.active,v.activatedAt,v.fibValue,v.name);}}`;
const DS=`pragma solidity ^0.8.20;interface IERC20{function transfer(address,uint256)external returns(bool);}contract PIEZDistributor{address public owner;address public piezToken;mapping(uint8=>uint256)public levelAllocation;constructor(address t){owner=msg.sender;piezToken=t;levelAllocation[1]=1000 ether;levelAllocation[2]=1618 ether;}modifier onlyOwner(){require(msg.sender==owner);_;}function distribute(address to,uint8 l)external onlyOwner{IERC20(piezToken).transfer(to,levelAllocation[l]);}}`;
const out=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources:{'R.sol':{content:RS},'D.sol':{content:DS}},settings:{outputSelection:{'*':{'*':['abi','evm.bytecode']}}}})));
if(out.errors){const e=out.errors.filter(x=>x.severity==='error');if(e.length){console.error(e);process.exit(1);}}
const reg=out.contracts['R.sol']['UUONLevelRegistry'];
const dist=out.contracts['D.sol']['PIEZDistributor'];
console.log('Compiled');
const p=new ethers.JsonRpcProvider('https://mainnet.base.org');
const w=new ethers.Wallet(process.env.PRIVATE_KEY,p);
const rf=new ethers.ContractFactory(reg.abi,'0x'+reg.evm.bytecode.object,w);
const r=await rf.deploy('0x29b056EF63867BECe07DA46c470aC168154EF275');
console.log('Registry TX:',r.deploymentTransaction().hash);
await r.waitForDeployment();
const ra=await r.getAddress();
console.log('Registry:',ra);
const df=new ethers.ContractFactory(dist.abi,'0x'+dist.evm.bytecode.object,w);
const d=await df.deploy('0xfb9c83432331EAf6f4a9D9488828823587d6f3da');
console.log('Distributor TX:',d.deploymentTransaction().hash);
await d.waitForDeployment();
const da=await d.getAddress();
console.log('Distributor:',da);
const rc=new ethers.Contract(ra,reg.abi,w);
const t1=await rc.activateLevel(1);await t1.wait();
console.log('Level 1:',t1.hash);
const t2=await rc.activateLevel(2);await t2.wait();
console.log('Level 2:',t2.hash);
console.log('DONE');
console.log('Registry:',ra);
console.log('Distributor:',da);
