import React, { useState, useEffect, Suspense, lazy } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ExternalLink, Play, BookOpen, Code, Microscope, X, ArrowLeft, Atom } from 'lucide-react';

const MathVisualizer = lazy(() => import('../components/MathVisualizer'));

interface ShapeData {
  name: string;
  category: string;
  description: string;
  whatIsIt: string;
  whyItMatters: string[];
  applications: string[];
  technicalDetails: {
    equation: string;
    parameters: string[];
    properties: string[];
  };
  relatedShapes: string[];
}

const SHAPE_CONTENT: Record<string, ShapeData> = {
  'sphere': {
    name: 'Perfect Sphere',
    category: 'Basic Shapes',
    description: 'A mathematically perfect sphere with uniform curvature. The most fundamental 3D geometric primitive, representing symmetry and optimization in nature.',
    whatIsIt: 'A sphere is the set of all points equidistant from a center point. In differential geometry, it has constant positive Gaussian curvature and is the solution to many optimization problems.',
    whyItMatters: [
      'Minimal surface area for a given volume (soap bubbles, cells)',
      'Appears throughout nature (planets, atoms, droplets)',
      'Fundamental to physics (spherical coordinates, field equations)',
      'Used in engineering for bearings, tanks, and pressure vessels'
    ],
    applications: [
      'Molecular modeling',
      'Aerospace engineering',
      'Architecture',
      'Physics simulations'
    ],
    technicalDetails: {
      equation: 'x² + y² + z² = r²',
      parameters: ['radius r', 'center (x₀, y₀, z₀)'],
      properties: ['Genus 0', 'Gaussian curvature K = 1/r²', 'Surface area = 4πr²', 'Volume = (4/3)πr³']
    },
    relatedShapes: ['Ellipsoid', 'Torus', 'Geodesic Sphere']
  },
  'torus': {
    name: 'Torus',
    category: 'Basic Shapes',
    description: 'A donut-shaped surface of revolution generated by rotating a circle about an axis coplanar with the circle.',
    whatIsIt: 'The torus is a genus-1 surface, meaning it has one hole. It serves as a fundamental example in topology and appears in magnetic confinement fusion reactors.',
    whyItMatters: [
      'Fundamental shape in topology (genus 1 surface)',
      'Used in magnetic confinement fusion (tokamaks)',
      'Appears in architecture and design',
      'Important in mathematical knot theory'
    ],
    applications: [
      'Fusion reactor design',
      'Jewelry design',
      'Architecture',
      'Magnetic field containment'
    ],
    technicalDetails: {
      equation: '(√(x² + y²) - R)² + z² = r²',
      parameters: ['Major radius R', 'Minor radius r'],
      properties: ['Genus 1', 'Euler characteristic χ = 0', 'Surface area = 4π²Rr', 'Volume = 2π²Rr²']
    },
    relatedShapes: ['Sphere', 'Klein Bottle', 'Trefoil Knot']
  },
  'klein_bottle': {
    name: 'Klein Bottle',
    category: 'Topological Surfaces',
    description: 'A non-orientable surface with no inside or outside, famously requiring four dimensions to be constructed without self-intersection.',
    whatIsIt: 'The Klein bottle is a closed non-orientable surface that cannot be embedded in three-dimensional Euclidean space without self-intersection. It is formed by connecting two Möbius strips along their boundaries.',
    whyItMatters: [
      'Demonstrates non-orientable topology',
      'Important in theoretical physics',
      'Foundational in algebraic topology',
      'Illustrates 4D geometry concepts'
    ],
    applications: [
      'Topology research',
      'Mathematical education',
      'Theoretical physics',
      'Art and design'
    ],
    technicalDetails: {
      equation: 'Immersion in ℝ³ with self-intersection',
      parameters: ['Scale factor', 'Twist parameter'],
      properties: ['Non-orientable', 'Euler characteristic χ = 0', 'No boundary', 'Genus 1 (non-orientable)']
    },
    relatedShapes: ['Möbius Strip', 'Real Projective Plane', 'Torus']
  },
  'mobius_strip': {
    name: 'Möbius Strip',
    category: 'Topological Surfaces',
    description: 'A surface with only one side and one boundary curve, created by twisting a rectangular strip and joining the ends.',
    whatIsIt: 'The Möbius strip is the simplest non-orientable surface. It has the remarkable property that an ant walking along its surface would return to its starting point having traversed both "sides" without crossing an edge.',
    whyItMatters: [
      'Simplest non-orientable surface',
      'Used in conveyor belts for even wear',
      'Fundamental in topology education',
      'Appears in molecular structures'
    ],
    applications: [
      'Continuous-loop recording tapes',
      'Conveyor belts',
      'Mathematical education',
      'Art installations'
    ],
    technicalDetails: {
      equation: 'x(u,v) = (1 + v/2 cos(u/2)) cos(u)',
      parameters: ['u ∈ [0, 2π]', 'v ∈ [-1, 1]'],
      properties: ['Non-orientable', 'One boundary', 'Euler characteristic χ = 0', 'Half-twist']
    },
    relatedShapes: ['Klein Bottle', 'Real Projective Plane', 'Cross-cap']
  },
  'lorenz_attractor': {
    name: 'Lorenz Attractor',
    category: 'Chaos Theory',
    description: 'The butterfly-shaped strange attractor arising from the Lorenz system of differential equations, a landmark in chaos theory.',
    whatIsIt: 'The Lorenz attractor is a set of chaotic solutions to a simplified model of atmospheric convection. It demonstrates sensitive dependence on initial conditions - the "butterfly effect."',
    whyItMatters: [
      'Foundation of chaos theory',
      'Demonstrates the butterfly effect',
      'Important for weather prediction understanding',
      'Shows deterministic chaos'
    ],
    applications: [
      'Weather modeling',
      'Chaos theory research',
      'Cryptography',
      'Signal processing'
    ],
    technicalDetails: {
      equation: 'dx/dt = σ(y-x), dy/dt = x(ρ-z)-y, dz/dt = xy-βz',
      parameters: ['σ = 10', 'ρ = 28', 'β = 8/3'],
      properties: ['Strange attractor', 'Fractal dimension ≈ 2.06', 'Sensitive dependence', 'Bounded trajectories']
    },
    relatedShapes: ['Rössler Attractor', 'Hénon Map', 'Double Pendulum']
  },
  'gyroid': {
    name: 'Gyroid',
    category: 'TPMS / Minimal Surfaces',
    description: 'A triply periodic minimal surface (TPMS) with no straight lines and no reflectional symmetries, found in biological structures.',
    whatIsIt: 'The gyroid is a minimal surface discovered by Alan Schoen in 1970. It divides space into two congruent labyrinthine regions and appears naturally in butterfly wing scales.',
    whyItMatters: [
      'Found in butterfly wing structures',
      'Optimal for heat exchange',
      'Used in 3D printing lattices',
      'Self-supporting geometry'
    ],
    applications: [
      '3D printed bone scaffolds',
      'Heat exchangers',
      'Acoustic materials',
      'Lightweight structures'
    ],
    technicalDetails: {
      equation: 'sin(x)cos(y) + sin(y)cos(z) + sin(z)cos(x) = 0',
      parameters: ['Period a', 'Thickness t'],
      properties: ['Mean curvature H = 0', 'Triply periodic', 'No straight lines', 'Cubic symmetry']
    },
    relatedShapes: ['Schwarz P', 'Schwarz D', 'Lidinoid']
  },
  'catenoid': {
    name: 'Catenoid',
    category: 'Minimal Surfaces',
    description: 'The surface of revolution generated by rotating a catenary curve. The first non-trivial minimal surface discovered.',
    whatIsIt: 'The catenoid was discovered by Leonhard Euler in 1744. It is the shape that soap film takes between two parallel circular rings and minimizes surface area for the given boundary.',
    whyItMatters: [
      'First discovered minimal surface',
      'Appears in soap film experiments',
      'Models bridge cable shapes',
      'Foundation of minimal surface theory'
    ],
    applications: [
      'Architectural design',
      'Tensile structures',
      'Soap bubble research',
      'Surface optimization'
    ],
    technicalDetails: {
      equation: 'x = c cosh(z/c) cos(θ), y = c cosh(z/c) sin(θ)',
      parameters: ['c (scale)', 'θ ∈ [0, 2π]', 'z ∈ [-h, h]'],
      properties: ['Mean curvature H = 0', 'Surface of revolution', 'Locally isometric to helicoid', 'Gaussian curvature K < 0']
    },
    relatedShapes: ['Helicoid', 'Costa Surface', 'Enneper Surface']
  },
  'hypercube': {
    name: '4D Hypercube (Tesseract)',
    category: '4D Polytopes',
    description: 'The four-dimensional analog of the cube, consisting of 8 cubic cells, 24 square faces, 32 edges, and 16 vertices.',
    whatIsIt: 'A tesseract is to a cube what a cube is to a square. It exists in 4D space and can only be visualized in 3D through projection, similar to how we draw a 3D cube on 2D paper.',
    whyItMatters: [
      'Fundamental 4D geometry',
      'Used in theoretical physics',
      'Demonstrates higher dimensions',
      'Important in data visualization'
    ],
    applications: [
      'String theory',
      'Data visualization',
      'Computer graphics',
      'Mathematical education'
    ],
    technicalDetails: {
      equation: '|x₁| ≤ 1, |x₂| ≤ 1, |x₃| ≤ 1, |x₄| ≤ 1',
      parameters: ['Edge length', 'Rotation angles (6 planes)'],
      properties: ['8 cubic cells', '24 square faces', '32 edges', '16 vertices']
    },
    relatedShapes: ['16-cell', '24-cell', '120-cell']
  }
};

export default function ShapeContentPage() {
  const { shapeId } = useParams<{ shapeId: string }>();
  const [showTool, setShowTool] = useState(false);
  
  const normalizedId = shapeId?.toLowerCase().replace(/-/g, '_') || 'sphere';
  const shape = SHAPE_CONTENT[normalizedId] || SHAPE_CONTENT['sphere'];

  useEffect(() => {
    document.title = `${shape.name} - Δmension Mathematical Universe`;
  }, [shape.name]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900/50 to-slate-900 text-white">
      {/* Header */}
      <header className="border-b border-purple-500/30 bg-black/50 backdrop-blur sticky top-0 z-40">
        <div className="container mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-3">
            <img src="/dmension-logo.png" alt="Δmension" className="w-10 h-10 rounded-lg" />
            <div>
              <h1 className="text-xl font-bold">Δmension</h1>
              <p className="text-xs text-purple-300">Mathematical Universe</p>
            </div>
          </Link>
          <nav className="flex gap-6 text-sm">
            <Link to="/" className="hover:text-purple-300 transition flex items-center gap-1">
              <ArrowLeft size={16} />
              Back to App
            </Link>
            <Link to="/museum" className="hover:text-purple-300 transition">Gallery</Link>
            <Link to="/sdk-portal" className="hover:text-purple-300 transition">API</Link>
          </nav>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-6 py-12">
        {/* Hero Section */}
        <div className="grid lg:grid-cols-2 gap-12 mb-16">
          <div>
            <div className="text-sm text-purple-300 mb-2">{shape.category}</div>
            <h1 className="text-5xl font-bold mb-6 bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
              {shape.name}
            </h1>
            <p className="text-xl text-slate-300 mb-8 leading-relaxed">
              {shape.description}
            </p>
            
            {/* CTA Buttons */}
            <div className="flex gap-4 flex-wrap">
              <button 
                onClick={() => setShowTool(true)}
                className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-purple-600 to-pink-600 rounded-lg font-semibold hover:from-purple-500 hover:to-pink-500 transition transform hover:scale-105"
              >
                <Play size={20} />
                Generate 3D Model
              </button>
              <Link 
                to="/sdk-portal" 
                className="flex items-center gap-2 px-6 py-3 bg-slate-800 rounded-lg font-semibold hover:bg-slate-700 transition"
              >
                <Code size={20} />
                View API Docs
              </Link>
            </div>
          </div>

          {/* Visual Preview */}
          <div className="bg-slate-800/50 rounded-2xl p-8 border border-purple-500/30">
            <div className="aspect-square bg-gradient-to-br from-purple-900/50 to-pink-900/50 rounded-xl flex items-center justify-center">
              <div className="text-center">
                <Atom className="w-24 h-24 text-purple-400 mx-auto mb-4 animate-pulse" />
                <p className="text-slate-400">Interactive 3D Preview</p>
                <button 
                  onClick={() => setShowTool(true)}
                  className="mt-4 px-4 py-2 bg-purple-600 rounded-lg text-sm hover:bg-purple-500 transition"
                >
                  Click to explore
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* What Is It Section */}
        <section className="mb-12 bg-slate-800/30 rounded-2xl p-8 border border-purple-500/20">
          <div className="flex items-center gap-3 mb-4">
            <BookOpen className="text-purple-400" size={24} />
            <h2 className="text-2xl font-bold">What Is It?</h2>
          </div>
          <p className="text-slate-300 leading-relaxed text-lg">
            {shape.whatIsIt}
          </p>
        </section>

        {/* Why It Matters */}
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-6 flex items-center gap-3">
            <Microscope className="text-purple-400" size={24} />
            Why It Matters
          </h2>
          <div className="grid md:grid-cols-2 gap-4">
            {shape.whyItMatters.map((reason, idx) => (
              <div key={idx} className="bg-slate-800/30 rounded-xl p-6 border border-purple-500/20">
                <div className="flex items-start gap-3">
                  <div className="w-8 h-8 rounded-full bg-purple-600 flex items-center justify-center text-sm font-bold flex-shrink-0">
                    {idx + 1}
                  </div>
                  <p className="text-slate-300">{reason}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Technical Details */}
        <section className="mb-12 bg-slate-800/30 rounded-2xl p-8 border border-purple-500/20">
          <h2 className="text-2xl font-bold mb-6">Technical Specifications</h2>
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-semibold text-purple-300 mb-2">Mathematical Equation</h3>
              <code className="block bg-black/50 p-4 rounded-lg text-green-400 font-mono text-lg">
                {shape.technicalDetails.equation}
              </code>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-purple-300 mb-2">Parameters</h3>
              <div className="flex flex-wrap gap-2">
                {shape.technicalDetails.parameters.map((param, idx) => (
                  <span key={idx} className="px-4 py-2 bg-purple-900/50 rounded-full text-sm border border-purple-500/30">
                    {param}
                  </span>
                ))}
              </div>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-purple-300 mb-2">Properties</h3>
              <ul className="grid md:grid-cols-2 gap-2">
                {shape.technicalDetails.properties.map((prop, idx) => (
                  <li key={idx} className="flex items-center gap-2">
                    <div className="w-2 h-2 bg-purple-400 rounded-full"></div>
                    <span className="text-slate-300">{prop}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </section>

        {/* Applications */}
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-6">Real-World Applications</h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
            {shape.applications.map((app, idx) => (
              <div key={idx} className="bg-gradient-to-br from-purple-900/30 to-pink-900/30 rounded-xl p-6 border border-purple-500/30 hover:border-purple-400 transition">
                <p className="text-center font-semibold">{app}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Related Shapes */}
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-6">Related Shapes</h2>
          <div className="flex flex-wrap gap-3">
            {shape.relatedShapes.map((related, idx) => (
              <Link
                key={idx}
                to={`/shapes/${related.toLowerCase().replace(/\s+/g, '_')}`}
                className="px-4 py-2 bg-slate-800 rounded-lg hover:bg-purple-900/50 transition border border-purple-500/30 flex items-center gap-2"
              >
                {related}
                <ExternalLink size={16} />
              </Link>
            ))}
          </div>
        </section>

        {/* CTA Section */}
        <section className="bg-gradient-to-r from-purple-900/50 to-pink-900/50 rounded-2xl p-12 border border-purple-500/30 text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to Explore?</h2>
          <p className="text-slate-300 mb-8 max-w-2xl mx-auto">
            Generate this shape interactively with full parameter control. Rotate, scale, and export in multiple formats.
          </p>
          <button 
            onClick={() => setShowTool(true)}
            className="inline-flex items-center gap-2 px-8 py-4 bg-gradient-to-r from-purple-600 to-pink-600 rounded-xl font-bold text-lg hover:from-purple-500 hover:to-pink-500 transition transform hover:scale-105"
          >
            <Play size={24} />
            Generate 3D Model Now
          </button>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-purple-500/30 bg-black/30 mt-16">
        <div className="container mx-auto px-6 py-8 text-center text-slate-400">
          <p>UUON Foundation Inc. | Δmension Mathematical Universe</p>
          <p className="text-sm mt-2">2,677 parametric shapes | 2,302 mathematical equations</p>
        </div>
      </footer>

      {/* Modal for 3D Tool */}
      {showTool && (
        <div className="fixed inset-0 bg-black/90 backdrop-blur flex items-center justify-center z-50 p-4">
          <div className="bg-slate-900 rounded-2xl border border-purple-500 w-full max-w-7xl h-[90vh] overflow-hidden flex flex-col">
            <div className="p-4 border-b border-purple-500/30 flex items-center justify-between flex-shrink-0">
              <h3 className="text-xl font-bold flex items-center gap-2">
                <Atom className="text-purple-400" />
                {shape.name} - Interactive Generator
              </h3>
              <button 
                onClick={() => setShowTool(false)}
                className="p-2 hover:bg-slate-800 rounded-lg transition"
              >
                <X size={24} />
              </button>
            </div>
            <div className="flex-1 overflow-hidden">
              <Suspense fallback={
                <div className="h-full flex items-center justify-center">
                  <div className="text-center">
                    <div className="w-16 h-16 border-4 border-purple-500/30 border-t-purple-500 rounded-full animate-spin mx-auto mb-4" />
                    <p className="text-slate-400">Loading 3D Visualizer...</p>
                  </div>
                </div>
              }>
                <MathVisualizer />
              </Suspense>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
