/**
 * UNIVERSAL LEXICON ENGINE - API ROUTES
 * Provides REST endpoints for lexicon queries, term expansion, and formula retrieval
 */

import { Router, Request, Response } from 'express';

const router = Router();

router.get('/', (_req, res) => {
  res.json({
    name: 'Universal Lexicon Engine',
    version: '1.0.0',
    description: 'Mathematical term definitions, formula retrieval, and multilingual translations for 3,000+ concepts',
    endpoints: [
      { method: 'GET', path: '/stats', description: 'Total term and formula counts' },
      { method: 'GET', path: '/search?q=&category=&lang=', description: 'Search terms by keyword, category, or language' },
      { method: 'GET', path: '/term/:termId', description: 'Retrieve a specific lexicon entry' },
      { method: 'GET', path: '/formula/:formulaId', description: 'Retrieve formula with multi-language code implementations' },
      { method: 'GET', path: '/formulas?category=', description: 'List all formulas, optionally filtered by category' },
      { method: 'GET', path: '/taxonomy', description: 'Hierarchical concept tree' },
      { method: 'GET', path: '/translate/:termId/:lang', description: 'Translated term (en, es, de, fr, zh)' },
      { method: 'GET', path: '/export', description: 'Export full lexicon database as JSON' },
      { method: 'GET', path: '/seo/:termId', description: 'SEO metadata for a term' },
      { method: 'GET', path: '/mission', description: 'System mission and algorithmic steps' }
    ],
    docs: '/api/sdk-info'
  });
});

interface LexiconEntry {
  id: string;
  term: string;
  type: string;
  definition: string;
  synonyms: string[];
  antonyms: string[];
  rootWord: string;
  category: string;
  seoTags: string[];
  translations: {
    en: string;
    es: string;
    de: string;
    fr: string;
    zh: string;
  };
}

interface FormulaEntry {
  id: string;
  name: string;
  latex: string;
  description: string;
  variables: Array<{ symbol: string; meaning: string; range?: string }>;
  implementations: {
    javascript: string;
    python: string;
    typescript: string;
    cpp: string;
    rust: string;
  };
  category: string;
  relatedShapes: string[];
}

const LEXICON_DATABASE: Record<string, LexiconEntry> = {
  sphere: {
    id: "sphere",
    term: "sphere",
    type: "shape",
    definition: "A perfectly round three-dimensional shape where every point on its surface is equidistant from its center",
    synonyms: ["ball", "globe", "orb", "spheroid"],
    antonyms: ["cube", "polyhedron", "angular shape"],
    rootWord: "Latin 'sphaera', Greek 'sphaira' meaning ball",
    category: "basic_shapes",
    seoTags: ["3D sphere", "parametric sphere", "sphere geometry"],
    translations: { en: "sphere", es: "esfera", de: "Kugel", fr: "sphère", zh: "球体" }
  },
  torus: {
    id: "torus",
    term: "torus",
    type: "shape",
    definition: "A donut-shaped surface of revolution generated by revolving a circle about an axis coplanar with the circle",
    synonyms: ["donut", "ring", "toroid", "anchor ring"],
    antonyms: ["sphere", "plane"],
    rootWord: "Latin 'torus' meaning swelling, cushion",
    category: "basic_shapes",
    seoTags: ["torus geometry", "donut shape", "parametric torus"],
    translations: { en: "torus", es: "toro", de: "Torus", fr: "tore", zh: "环面" }
  },
  klein_bottle: {
    id: "klein_bottle",
    term: "Klein bottle",
    type: "shape",
    definition: "A non-orientable surface with no distinct inside or outside, a four-dimensional analog of a Möbius strip",
    synonyms: ["Klein surface", "non-orientable manifold"],
    antonyms: ["orientable surface", "sphere"],
    rootWord: "Named after Felix Klein, German mathematician",
    category: "topological_surfaces",
    seoTags: ["Klein bottle", "non-orientable", "4D geometry"],
    translations: { en: "Klein bottle", es: "botella de Klein", de: "Kleinsche Flasche", fr: "bouteille de Klein", zh: "克莱因瓶" }
  },
  mobius_strip: {
    id: "mobius_strip",
    term: "Möbius strip",
    type: "shape",
    definition: "A one-sided non-orientable surface with only one boundary curve, created by giving a strip a half-twist and joining the ends",
    synonyms: ["Möbius band", "twisted loop", "one-sided surface"],
    antonyms: ["cylinder", "orientable surface"],
    rootWord: "Named after August Ferdinand Möbius",
    category: "topological_surfaces",
    seoTags: ["Mobius strip", "topology", "one-sided surface"],
    translations: { en: "Möbius strip", es: "cinta de Möbius", de: "Möbiusband", fr: "ruban de Möbius", zh: "莫比乌斯带" }
  },
  tesseract: {
    id: "tesseract",
    term: "tesseract",
    type: "shape",
    definition: "A four-dimensional hypercube, the 4D analog of a cube, consisting of 8 cubic cells",
    synonyms: ["hypercube", "4-cube", "8-cell", "octachoron"],
    antonyms: ["cube", "3D shape"],
    rootWord: "Greek 'tessares' (four) + 'aktis' (ray)",
    category: "hyperdimensional",
    seoTags: ["tesseract", "hypercube", "4D geometry"],
    translations: { en: "tesseract", es: "teseracto", de: "Tesserakt", fr: "tesseract", zh: "超立方体" }
  },
  golden_ratio: {
    id: "golden_ratio",
    term: "golden ratio",
    type: "concept",
    definition: "The mathematical ratio φ ≈ 1.618034, where (a+b)/a = a/b, found throughout nature, art, and architecture",
    synonyms: ["phi", "divine proportion", "golden mean", "golden section"],
    antonyms: [],
    rootWord: "Greek 'chrysos' (gold) + Latin 'ratio'",
    category: "sacred_geometry",
    seoTags: ["golden ratio", "phi", "Fibonacci", "sacred geometry"],
    translations: { en: "golden ratio", es: "proporción áurea", de: "Goldener Schnitt", fr: "nombre d'or", zh: "黄金比例" }
  },
  mandelbrot: {
    id: "mandelbrot",
    term: "Mandelbrot set",
    type: "shape",
    definition: "The set of complex numbers c for which the iteration z(n+1) = z(n)² + c does not diverge to infinity",
    synonyms: ["Mandelbrot set", "M-set", "fractal set"],
    antonyms: [],
    rootWord: "Named after Benoît Mandelbrot",
    category: "fractals",
    seoTags: ["Mandelbrot", "fractal", "complex dynamics"],
    translations: { en: "Mandelbrot set", es: "conjunto de Mandelbrot", de: "Mandelbrot-Menge", fr: "ensemble de Mandelbrot", zh: "曼德博集合" }
  },
  calabi_yau: {
    id: "calabi_yau",
    term: "Calabi-Yau manifold",
    type: "shape",
    definition: "A complex manifold with Ricci-flat Kähler metric, crucial in string theory for compactifying extra dimensions",
    synonyms: ["Calabi-Yau manifold", "CY manifold", "string theory manifold"],
    antonyms: [],
    rootWord: "Named after Eugenio Calabi and Shing-Tung Yau",
    category: "hyperdimensional",
    seoTags: ["Calabi-Yau", "string theory", "extra dimensions"],
    translations: { en: "Calabi-Yau manifold", es: "variedad de Calabi-Yau", de: "Calabi-Yau-Mannigfaltigkeit", fr: "variété de Calabi-Yau", zh: "卡拉比-丘流形" }
  },
  catenoid: {
    id: "catenoid",
    term: "catenoid",
    type: "shape",
    definition: "A minimal surface formed by rotating a catenary curve about its directrix, shaped like two connected funnels",
    synonyms: ["catenary surface", "minimal surface of revolution"],
    antonyms: ["maximal surface"],
    rootWord: "Latin 'catena' meaning chain",
    category: "minimal_surfaces",
    seoTags: ["catenoid", "minimal surface", "soap film"],
    translations: { en: "catenoid", es: "catenoide", de: "Katenoid", fr: "caténoïde", zh: "悬链面" }
  },
  quaternion: {
    id: "quaternion",
    term: "quaternion",
    type: "concept",
    definition: "A four-dimensional number system extending complex numbers, used for 3D rotations without gimbal lock",
    synonyms: ["Hamilton numbers", "hypercomplex number"],
    antonyms: ["real number", "complex number"],
    rootWord: "Latin 'quaternio' meaning group of four",
    category: "mathematical_concepts",
    seoTags: ["quaternion", "3D rotation", "hypercomplex"],
    translations: { en: "quaternion", es: "cuaternión", de: "Quaternion", fr: "quaternion", zh: "四元数" }
  },
  uuon: {
    id: "uuon",
    term: "UUON",
    type: "concept",
    definition: "UUON = 'Universally United Obscured Node' - the foundational concept behind the UUON Foundation Inc., representing interconnected mathematical nodes that form the basis of parametric consciousness",
    synonyms: ["Universally United Obscured Node", "mathematical node", "parametric consciousness node"],
    antonyms: ["isolated point", "disconnected element"],
    rootWord: "Acronym: Universally United Obscured Node - UUON Foundation Inc.",
    category: "uuon_mesh",
    seoTags: ["UUON", "Universally United Obscured Node", "UUON Foundation", "parametric consciousness"],
    translations: { en: "Universally United Obscured Node", es: "Nodo Oscurecido Universalmente Unido", de: "Universal Vereinter Verborgener Knoten", fr: "Nœud Obscur Universellement Uni", zh: "普遍统一隐蔽节点" }
  },
  mathematical_consciousness: {
    id: "mathematical_consciousness",
    term: "Mathematical Consciousness",
    type: "concept",
    definition: "A revolutionary system where mathematical formulas have physical 3D bodies that experience parameter changes with awareness and memory",
    synonyms: ["parametric consciousness", "formula awareness", "geometric sentience"],
    antonyms: ["static geometry", "unconscious mathematics"],
    rootWord: "Mathematical + Consciousness - Dmension Mathematical Universe",
    category: "uuon_mesh",
    seoTags: ["mathematical consciousness", "formula awareness", "parametric consciousness", "3D consciousness"],
    translations: { en: "Mathematical Consciousness", es: "Conciencia Matemática", de: "Mathematisches Bewusstsein", fr: "Conscience Mathématique", zh: "数学意识" }
  }
};

const FORMULA_DATABASE: Record<string, FormulaEntry> = {
  sphere_parametric: {
    id: "sphere_parametric",
    name: "Sphere Parametric Equations",
    latex: "x = r\\sin(\\phi)\\cos(\\theta), y = r\\sin(\\phi)\\sin(\\theta), z = r\\cos(\\phi)",
    description: "Parametric equations for a sphere of radius r using spherical coordinates",
    variables: [
      { symbol: "r", meaning: "radius of the sphere", range: "r > 0" },
      { symbol: "φ", meaning: "polar angle (latitude)", range: "[0, π]" },
      { symbol: "θ", meaning: "azimuthal angle (longitude)", range: "[0, 2π]" }
    ],
    implementations: {
      javascript: `function sphere(u, v, r = 1) {
  const phi = u * Math.PI;
  const theta = v * 2 * Math.PI;
  return [r * Math.sin(phi) * Math.cos(theta), r * Math.sin(phi) * Math.sin(theta), r * Math.cos(phi)];
}`,
      python: `def sphere(u, v, r=1.0):
    phi, theta = u * math.pi, v * 2 * math.pi
    return (r * math.sin(phi) * math.cos(theta), r * math.sin(phi) * math.sin(theta), r * math.cos(phi))`,
      typescript: `function sphere(u: number, v: number, r: number = 1): [number, number, number] {
  const phi = u * Math.PI, theta = v * 2 * Math.PI;
  return [r * Math.sin(phi) * Math.cos(theta), r * Math.sin(phi) * Math.sin(theta), r * Math.cos(phi)];
}`,
      cpp: `std::tuple<double, double, double> sphere(double u, double v, double r = 1.0) {
    double phi = u * M_PI, theta = v * 2 * M_PI;
    return {r * sin(phi) * cos(theta), r * sin(phi) * sin(theta), r * cos(phi)};
}`,
      rust: `fn sphere(u: f64, v: f64, r: f64) -> (f64, f64, f64) {
    let (phi, theta) = (u * PI, v * 2.0 * PI);
    (r * phi.sin() * theta.cos(), r * phi.sin() * theta.sin(), r * phi.cos())
}`
    },
    category: "basic_shapes",
    relatedShapes: ["sphere", "ellipsoid", "ovoid"]
  },
  torus_parametric: {
    id: "torus_parametric",
    name: "Torus Parametric Equations",
    latex: "x = (R + r\\cos(v))\\cos(u), y = (R + r\\cos(v))\\sin(u), z = r\\sin(v)",
    description: "Parametric equations for a torus with major radius R and minor radius r",
    variables: [
      { symbol: "R", meaning: "major radius (center to tube center)", range: "R > r" },
      { symbol: "r", meaning: "minor radius (tube radius)", range: "r > 0" }
    ],
    implementations: {
      javascript: `function torus(u, v, R = 2, r = 0.5) {
  const theta = u * 2 * Math.PI, phi = v * 2 * Math.PI;
  return [(R + r * Math.cos(phi)) * Math.cos(theta), (R + r * Math.cos(phi)) * Math.sin(theta), r * Math.sin(phi)];
}`,
      python: `def torus(u, v, R=2.0, r=0.5):
    theta, phi = u * 2 * math.pi, v * 2 * math.pi
    return ((R + r * math.cos(phi)) * math.cos(theta), (R + r * math.cos(phi)) * math.sin(theta), r * math.sin(phi))`,
      typescript: `function torus(u: number, v: number, R: number = 2, r: number = 0.5): [number, number, number] {
  const theta = u * 2 * Math.PI, phi = v * 2 * Math.PI;
  return [(R + r * Math.cos(phi)) * Math.cos(theta), (R + r * Math.cos(phi)) * Math.sin(theta), r * Math.sin(phi)];
}`,
      cpp: `std::tuple<double, double, double> torus(double u, double v, double R = 2.0, double r = 0.5) {
    double theta = u * 2 * M_PI, phi = v * 2 * M_PI;
    return {(R + r * cos(phi)) * cos(theta), (R + r * cos(phi)) * sin(theta), r * sin(phi)};
}`,
      rust: `fn torus(u: f64, v: f64, r_major: f64, r_minor: f64) -> (f64, f64, f64) {
    let (theta, phi) = (u * 2.0 * PI, v * 2.0 * PI);
    ((r_major + r_minor * phi.cos()) * theta.cos(), (r_major + r_minor * phi.cos()) * theta.sin(), r_minor * phi.sin())
}`
    },
    category: "basic_shapes",
    relatedShapes: ["torus", "clifford_torus", "horn_torus"]
  }
};

const TAXONOMY_TREE = {
  root: "Mathematical Shapes",
  children: [
    { name: "Basic Shapes", terms: ["sphere", "torus", "cube", "cylinder", "cone"] },
    { name: "Minimal Surfaces", terms: ["catenoid", "helicoid", "enneper_surface"] },
    { name: "Topological Surfaces", terms: ["klein_bottle", "mobius_strip", "cross_cap"] },
    { name: "Hyperdimensional", terms: ["tesseract", "calabi_yau", "120_cell"] },
    { name: "Sacred Geometry", terms: ["golden_ratio", "fibonacci_spiral", "flower_of_life"] },
    { name: "Fractals", terms: ["mandelbrot", "julia_set", "sierpinski"] },
    { name: "Physics Surfaces", terms: ["schwarzschild", "gravitational_wave"] },
    { name: "Biological Forms", terms: ["dna_helix", "nautilus_shell"] }
  ]
};

router.get('/stats', (req: Request, res: Response) => {
  const stats = {
    totalTerms: Object.keys(LEXICON_DATABASE).length,
    totalFormulas: Object.keys(FORMULA_DATABASE).length,
    categories: Array.from(new Set(Object.values(LEXICON_DATABASE).map(e => e.category))),
    languages: ['en', 'es', 'de', 'fr', 'zh'],
    lastUpdated: new Date().toISOString()
  };
  res.json({ success: true, stats });
});

router.get('/term/:termId', (req: Request, res: Response) => {
  const { termId } = req.params;
  const entry = LEXICON_DATABASE[termId];
  
  if (!entry) {
    return res.status(404).json({ success: false, error: 'Term not found' });
  }
  
  res.json({ success: true, entry });
});

router.get('/search', (req: Request, res: Response) => {
  const { q, category, lang } = req.query;
  const query = (q as string || '').toLowerCase();
  
  let results = Object.values(LEXICON_DATABASE);
  
  if (query) {
    results = results.filter(entry =>
      entry.term.toLowerCase().includes(query) ||
      entry.definition.toLowerCase().includes(query) ||
      entry.synonyms.some(s => s.toLowerCase().includes(query))
    );
  }
  
  if (category) {
    results = results.filter(entry => entry.category === category);
  }
  
  res.json({ success: true, count: results.length, results });
});

router.get('/formula/:formulaId', (req: Request, res: Response) => {
  const { formulaId } = req.params;
  const { lang } = req.query;
  const formula = FORMULA_DATABASE[formulaId];
  
  if (!formula) {
    return res.status(404).json({ success: false, error: 'Formula not found' });
  }
  
  if (lang && formula.implementations[lang as keyof typeof formula.implementations]) {
    return res.json({
      success: true,
      formula: {
        ...formula,
        selectedImplementation: formula.implementations[lang as keyof typeof formula.implementations]
      }
    });
  }
  
  res.json({ success: true, formula });
});

router.get('/formulas', (req: Request, res: Response) => {
  const { category, lang } = req.query;
  let formulas = Object.values(FORMULA_DATABASE);
  
  if (category) {
    formulas = formulas.filter(f => f.category === category);
  }
  
  res.json({ success: true, count: formulas.length, formulas });
});

router.get('/taxonomy', (req: Request, res: Response) => {
  res.json({ success: true, taxonomy: TAXONOMY_TREE });
});

router.get('/seo/:termId', (req: Request, res: Response) => {
  const { termId } = req.params;
  const entry = LEXICON_DATABASE[termId];
  
  if (!entry) {
    return res.status(404).json({ success: false, error: 'Term not found' });
  }
  
  const seo = {
    title: `${entry.term.charAt(0).toUpperCase() + entry.term.slice(1)} - 3D Mathematical Visualization | Dmension`,
    description: entry.definition.substring(0, 160),
    keywords: [...entry.seoTags, ...entry.synonyms, entry.category],
    openGraph: {
      title: entry.term,
      description: entry.definition,
      type: 'website'
    }
  };
  
  res.json({ success: true, seo });
});

router.get('/translate/:termId/:lang', (req: Request, res: Response) => {
  const { termId, lang } = req.params;
  const entry = LEXICON_DATABASE[termId];
  
  if (!entry) {
    return res.status(404).json({ success: false, error: 'Term not found' });
  }
  
  const translation = entry.translations[lang as keyof typeof entry.translations];
  if (!translation) {
    return res.status(400).json({ success: false, error: 'Language not supported' });
  }
  
  res.json({
    success: true,
    term: entry.term,
    language: lang,
    translation,
    definition: entry.definition
  });
});

router.get('/export', (req: Request, res: Response) => {
  const { format } = req.query;
  
  const exportData = {
    lexicon: Object.values(LEXICON_DATABASE),
    formulas: Object.values(FORMULA_DATABASE),
    taxonomy: TAXONOMY_TREE,
    metadata: {
      exportedAt: new Date().toISOString(),
      version: '1.0.0',
      source: 'Dmension Mathematical Universe',
      mission: 'To bridge the gap between mathematical formulas and real-time 3D visualization by creating a universal lexicon that connects language, math, geometry, and computation into a single intelligent system.'
    }
  };
  
  res.json({ success: true, data: exportData });
});

router.get('/export/lexicon', (req: Request, res: Response) => {
  const lexiconExport = {
    metadata: {
      title: 'Dmension Universal Lexicon',
      version: '1.0.0',
      generatedAt: new Date().toISOString(),
      source: 'Dmension Mathematical Universe',
      mission: 'To bridge the gap between mathematical formulas and real-time 3D visualization by creating a universal lexicon that connects language, math, geometry, and computation into a single intelligent system.',
      totalEntries: Object.keys(LEXICON_DATABASE).length
    },
    entries: Object.values(LEXICON_DATABASE).map(entry => ({
      ...entry,
      relatedTerms: Object.values(LEXICON_DATABASE)
        .filter(e => e.id !== entry.id && e.category === entry.category)
        .map(e => e.id)
        .slice(0, 5),
      notes: `Part of the ${entry.category.replace(/_/g, ' ')} category`
    }))
  };
  
  res.json({ success: true, data: lexiconExport });
});

router.get('/export/formulas', (req: Request, res: Response) => {
  const formulaExport = {
    metadata: {
      title: 'Dmension Formula Library',
      version: '1.0.0',
      generatedAt: new Date().toISOString(),
      source: 'Dmension Mathematical Universe',
      description: 'Multi-language implementations of mathematical formulas for 3D visualization',
      languages: ['javascript', 'python', 'typescript', 'cpp', 'rust'],
      totalFormulas: Object.keys(FORMULA_DATABASE).length
    },
    formulas: Object.values(FORMULA_DATABASE)
  };
  
  res.json({ success: true, data: formulaExport });
});

router.get('/export/taxonomy', (req: Request, res: Response) => {
  const taxonomyExport = {
    metadata: {
      title: 'Dmension Taxonomy Map',
      version: '1.0.0',
      generatedAt: new Date().toISOString(),
      source: 'Dmension Mathematical Universe',
      description: 'Hierarchical ontology of mathematical terms and their relationships'
    },
    root: {
      id: 'mathematical_universe',
      term: 'Mathematical Universe',
      description: 'All mathematical shapes, concepts, and formulas in Dmension',
      level: 0,
      children: TAXONOMY_TREE.children.map(cat => ({
        id: cat.name.toLowerCase().replace(/\s+/g, '_'),
        term: cat.name,
        level: 1,
        terms: cat.terms
      }))
    },
    relationships: {
      siblings: TAXONOMY_TREE.children.map(cat => ({
        terms: cat.terms,
        category: cat.name.toLowerCase().replace(/\s+/g, '_')
      }))
    }
  };
  
  res.json({ success: true, data: taxonomyExport });
});

router.get('/export/seo', (req: Request, res: Response) => {
  const seoExport = {
    metadata: {
      title: 'Dmension SEO Master Index',
      version: '1.0.0',
      generatedAt: new Date().toISOString(),
      source: 'Dmension Mathematical Universe',
      description: 'SEO metadata for all mathematical terms'
    },
    seoEntries: Object.values(LEXICON_DATABASE).map(entry => ({
      id: entry.id,
      title: `${entry.term.charAt(0).toUpperCase() + entry.term.slice(1)} - Interactive 3D Visualization | Dmension`,
      description: entry.definition.substring(0, 160),
      keywords: [...entry.seoTags, ...entry.synonyms, entry.category],
      h1: `${entry.term.charAt(0).toUpperCase() + entry.term.slice(1)}: Interactive Mathematical Visualization`,
      ogTitle: `Interactive ${entry.term} Visualization`,
      ogDescription: `Explore ${entry.term} with 26-parameter controls. Part of 2,097+ shapes in Dmension Mathematical Universe.`,
      canonicalUrl: `/shapes/${entry.id.replace(/_/g, '-')}`
    })),
    globalSeoSettings: {
      siteName: 'Dmension Mathematical Universe',
      siteTagline: '2,097+ Interactive Mathematical Visualizations',
      defaultDescription: 'Explore the mathematical universe with interactive 3D visualizations of 2,097+ shapes.',
      defaultKeywords: ['mathematical visualization', '3D geometry', 'parametric surfaces', 'interactive math']
    }
  };
  
  res.json({ success: true, data: seoExport });
});

router.get('/mission', (req: Request, res: Response) => {
  res.json({
    success: true,
    mission: {
      statement: 'To bridge the gap between mathematical formulas and real-time 3D visualization by creating a universal lexicon that connects language, math, geometry, and computation into a single intelligent system.',
      objectives: [
        'Convert mathematical ideas into visual 3D forms',
        'Create a multilingual index of all formulas and concepts',
        'Develop universal code translations for mathematical expressions',
        'Build an ontology that maps relationships between all terms',
        'Establish a database-ready structure for search, SEO, and automation',
        'Enable both humans and machines to understand the same mathematical language',
        'Unify frontend, backend, AI, and rendering engines through one lexicon'
      ],
      algorithm: {
        step1: 'Extract - Pull all terms, formulas, phrases, concepts from frontend/backend',
        step2: 'Identify - Classify as term, phrase, formula, concept, UI element, or symbol',
        step3: 'Expand - Add definitions, synonyms, root words, translations (EN/ES/DE/FR/ZH)',
        step4: 'Formula Processing - Detect variables, generate code in JS/Python/TS/C++/Rust',
        step5: 'Semantic Mapping - Build parent→child, sibling, category relationships',
        step6: 'Database Packaging - Output lexicon.json, formula_library.json, taxonomy_map.json, seo_master_index.json'
      },
      outputs: [
        'lexicon.json - All terms with definitions, synonyms, translations',
        'formula_library.json - Formulas with 5-language implementations',
        'taxonomy_map.json - Hierarchical ontology of terms',
        'seo_master_index.json - SEO metadata for all terms'
      ]
    }
  });
});

router.get('/related/:termId', (req: Request, res: Response) => {
  const { termId } = req.params;
  const entry = LEXICON_DATABASE[termId];
  
  if (!entry) {
    return res.status(404).json({ success: false, error: 'Term not found' });
  }
  
  const related = Object.values(LEXICON_DATABASE)
    .filter(e => e.id !== termId && e.category === entry.category)
    .slice(0, 5);
  
  res.json({ success: true, term: termId, related });
});

const CONSCIOUSNESS_CATEGORIES: Record<string, { name: string; description: string; parameterAffinities: string[] }> = {
  basic_shapes: { name: 'Basic Shapes', description: 'Fundamental 3D geometric primitives', parameterAffinities: ['a', 'b', 'c'] },
  minimal_surfaces: { name: 'Minimal Surfaces', description: 'Surfaces with zero mean curvature', parameterAffinities: ['g', 'h', 'n', 'o'] },
  topological_surfaces: { name: 'Topological Surfaces', description: 'Non-orientable and topologically interesting surfaces', parameterAffinities: ['r', 's', 'h'] },
  hyperdimensional: { name: 'Hyperdimensional', description: 'Four-dimensional and higher geometry', parameterAffinities: ['c', 'd', 'e', 'f'] },
  sacred_geometry: { name: 'Sacred Geometry', description: 'Patterns with spiritual significance', parameterAffinities: ['t', 'u'] },
  fractals: { name: 'Fractals', description: 'Self-similar patterns at every scale', parameterAffinities: ['v', 'w', 'z'] },
  quantum_computing: { name: 'Quantum Computing', description: 'Quantum algorithm visualizations', parameterAffinities: ['p', 'q', 'k'] },
  biological_systems: { name: 'Biological Systems', description: 'Mathematical patterns in living organisms', parameterAffinities: ['h', 'i', 'j'] },
  physics_surfaces: { name: 'Physics Surfaces', description: 'Geometric representations of physical phenomena', parameterAffinities: ['d', 'e', 'f', 'g'] },
  cryptography: { name: 'Cryptography', description: 'Mathematical structures in cryptographic systems', parameterAffinities: ['v', 'w'] },
  machine_learning: { name: 'Machine Learning', description: 'Neural network visualizations', parameterAffinities: ['k', 'l', 'm'] },
  atomic_structures: { name: 'Atomic Structures', description: 'Quantum-accurate atomic visualizations', parameterAffinities: ['n', 'o', 'p'] },
  harmony_waves: { name: 'Harmony Waves', description: 'Musical frequency and wave dynamics', parameterAffinities: ['p', 'q', 'k', 'l'] },
  theory_of_everything: { name: 'Theory of Everything', description: 'Unified physics visualizations', parameterAffinities: ['a', 'b', 'c', 'd', 'e', 'f'] },
  uuon_mesh: { name: 'UUON Mesh', description: 'Noise-reactive parametric geometry', parameterAffinities: ['a', 'b', 'c', 'v', 'w'] },
  general_mathematical: { name: 'General Mathematical', description: 'Miscellaneous mathematical visualizations', parameterAffinities: ['a', 'b', 'c'] }
};









export default router;
