/**
 * FRACTAL SKIN GENERATOR
 * © UUON Foundation Inc. 2026 — Phillip Aguilar Ruiz III
 * All exports carry embedded Ellomental provenance.
 * MIT License for the interface. Proprietary: algorithm calibration, provenance chain.
 *
 * 14 physics algorithms: 8 EM field modes + 6 Spectral Element burn modes
 * Exports: OBJ (3D mesh), PNG (still), WebM (animation)
 * Every export: UUON copyright header + session hash + timestamp embedded
 */

import { useRef, useEffect, useState, useCallback } from "react";
import * as THREE from "three";

// ─── Algorithm Definitions ────────────────────────────────────────────────────

const EM_ALGORITHMS = [
  { id: "EM_PLANE",      label: "EM-PLANE-001",    info: "Plane wave — A sin(k·r − ωt). Organic interference patterns." },
  { id: "TEM",           label: "TEM-001",          info: "TEM00 mode. Smooth flowing surfaces." },
  { id: "TE",            label: "TE-001",            info: "TE10 mode. Structured geometric patterns." },
  { id: "TM",            label: "TM-001",            info: "TM11 mode. Radial symmetric patterns." },
  { id: "GAUSSIAN_BEAM", label: "GAUSSIAN-BEAM-001", info: "Focused beam profile." },
  { id: "HERMITE_GAUSS", label: "HERMITE-GAUSS-001", info: "Complex natural-looking textures." },
  { id: "LAGUERRE_GAUSS",label: "LAGUERRE-GAUSS-001",info: "Spiral / vortex textures." },
  { id: "SPHERICAL_H",   label: "SPHERICAL-H-001",   info: "Seamless spherical harmonic mapping." },
];

const SEM_ALGORITHMS = [
  { id: "GLL",        label: "GLL-001",        info: "Gauss-Lobatto-Legendre. Concentrated energy burn points." },
  { id: "GRL",        label: "GRL-001",        info: "Gauss-Radau-Legendre. Asymmetric directional burns." },
  { id: "GL",         label: "GL-001",         info: "Gauss-Legendre. Smooth thermal gradients." },
  { id: "MORTAR",     label: "MORTAR-001",     info: "Mortar elements. Fracture/crack burn patterns." },
  { id: "HP_SEM",     label: "HP-SEM-001",     info: "hp-refinement. Multi-scale energy cascades." },
  { id: "DG_SPECTRAL",label: "DG-SPECTRAL-001",info: "Discontinuous Galerkin. Cellular energy boundaries." },
];

const ALL_ALGOS = [...EM_ALGORITHMS, ...SEM_ALGORITHMS];
const SHAPES    = ["plane", "sphere", "box", "torus", "cylinder"];

// ─── Provenance ───────────────────────────────────────────────────────────────

function generateSessionHash(): string {
  // Lightweight client-side provenance token (mirrors Ellomental structure)
  // Full Ellomental hash generated server-side on /api/ellomental/verify
  const timestamp = Date.now();
  const seed      = `UUON-FSG-${timestamp}-Phillip-Aguilar-Ruiz-III`;
  let   hash      = 0;
  for (let i = 0; i < seed.length; i++) {
    hash = ((hash << 5) - hash) + seed.charCodeAt(i);
    hash |= 0;
  }
  return `UUON-${Math.abs(hash).toString(16).padStart(8, "0").toUpperCase()}-${timestamp.toString(36).toUpperCase()}`;
}

function buildProvenanceHeader(algo: string, shape: string, mode: string, codename: string, sessionHash: string): string {
  const now = new Date().toISOString();
  return [
    `# ══════════════════════════════════════════════════`,
    `# UUON Foundation Inc. — Fractal Skin Generator`,
    `# © 2026 Phillip Aguilar Ruiz III. All rights reserved.`,
    `# ──────────────────────────────────────────────────`,
    `# Provenance Token : ${sessionHash}`,
    `# Generated        : ${now}`,
    `# Algorithm        : ${algo}`,
    `# Shape            : ${shape}`,
    `# Render Mode      : ${mode}`,
    codename ? `# Codename         : ${codename}` : null,
    `# ──────────────────────────────────────────────────`,
    `# This file was generated by UUON Foundation tooling.`,
    `# Commercial use requires a license.`,
    `# License info     : https://github.com/UUON-Foundation/uuon-clouud`,
    `# Verify provenance: https://uuon-foundation.com/verify?token=${sessionHash}`,
    `# ══════════════════════════════════════════════════`,
    ``,
  ].filter(Boolean).join("\n");
}

// Embed provenance into PNG as a tEXt chunk in the filename and as
// invisible pixels in the bottom-left 8×1 strip (LSB steganography).
function stampCanvasProvenance(canvas: HTMLCanvasElement, sessionHash: string): void {
  const ctx = canvas.getContext("2d");
  if (!ctx) return;
  // Write hash bits into bottom-left 64 pixels — imperceptible at any zoom
  const hashBits = sessionHash.split("").map(c => c.charCodeAt(0).toString(2).padStart(8, "0")).join("").slice(0, 64);
  const imageData = ctx.getImageData(0, canvas.height - 1, 64, 1);
  for (let i = 0; i < 64; i++) {
    // Flip LSB of blue channel: visible change is ±1 out of 255, invisible
    imageData.data[i * 4 + 2] = (imageData.data[i * 4 + 2] & 0xFE) | parseInt(hashBits[i] || "0");
  }
  ctx.putImageData(imageData, 0, canvas.height - 1);
}

// ─── Field Math ───────────────────────────────────────────────────────────────

function calcField(x: number, y: number, z: number, algo: string, p: any): number {
  const { frequency, amplitude, phase, time } = p;
  const k = Math.max(0.1, frequency * 2 * Math.PI);
  const w = frequency * time;
  x = Math.max(-10, Math.min(10, x || 0));
  y = Math.max(-10, Math.min(10, y || 0));
  z = Math.max(-10, Math.min(10, z || 0));
  let r = 0;
  switch (algo) {
    case "EM_PLANE": { const rad = Math.sqrt(x*x+y*y+z*z); r = amplitude * Math.sin(k*rad - w + phase); break; }
    case "TEM":      { const e = Math.max(-50, -(x*x+y*y)/Math.max(0.1, 0.5+frequency*0.1)); r = amplitude * Math.exp(e) * Math.cos(k*z - w + phase); break; }
    case "TE":       { const f = Math.max(0.1, frequency); r = amplitude * Math.sin((Math.PI*x)/f) * Math.cos(k*z - w + phase); break; }
    case "TM":       { const rho = Math.sqrt(x*x+y*y), th = Math.atan2(y,x); r = amplitude * Math.sin(k*rho) * Math.cos(th - w + phase); break; }
    case "GAUSSIAN_BEAM": { const w0=Math.max(0.1,0.5+frequency*0.1), zR=Math.PI*w0*w0/Math.max(0.1,frequency), wz=w0*Math.sqrt(1+Math.pow(z/zR,2)); r = amplitude * Math.exp(Math.max(-50,-(x*x+y*y)/(wz*wz))) * Math.cos(k*z - w + phase); break; }
    case "HERMITE_GAUSS": { const wx=Math.max(0.1,0.3+frequency*0.05), wy=Math.max(0.1,0.4+frequency*0.05); r = amplitude * (2*x/wx) * (2*y/wy) * Math.exp(Math.max(-50,-(x*x/(wx*wx)+y*y/(wy*wy)))) * Math.cos(k*z - w + phase); break; }
    case "LAGUERRE_GAUSS": { const rho=Math.sqrt(x*x+y*y), phi=Math.atan2(y,x), wl=Math.max(0.1,0.4+frequency*0.1); r = amplitude * rho * Math.exp(Math.max(-50,-(rho*rho)/(wl*wl))) * Math.cos(2*phi + k*z - w + phase); break; }
    case "SPHERICAL_H":  { const rad=Math.max(0.001,Math.sqrt(x*x+y*y+z*z)), th=Math.acos(Math.max(-1,Math.min(1,z/rad))), phi=Math.atan2(y,x); r = amplitude * Math.sin(th)*Math.cos(2*phi) * Math.cos(k*rad - w + phase); break; }
    case "GLL": { const xi=Math.max(-1,Math.min(1,x)), eta=Math.max(-1,Math.min(1,y)); r = amplitude * (0.5*(3*xi*xi-1)) * (0.5*(3*eta*eta-1)) * Math.exp(-((xi*xi+eta*eta)*frequency)) * (1+Math.sin(time*5)); break; }
    case "GRL": { const u=Math.tanh(x*frequency), v=Math.tanh(y*frequency); r = amplitude * Math.pow(u*u+v*v,0.5) * Math.exp(-Math.abs(u*v)*frequency) * 0.5*(1+Math.sin(time*8+phase)); break; }
    case "GL":  { const rad=Math.sqrt(x*x+y*y); r = amplitude * Math.exp(-rad*frequency*0.5) * (1-rad*0.3) * (1 + 0.5*Math.sin(k*rad-w*2+phase)*Math.cos(time*3)); break; }
    case "MORTAR": { const fx=Math.floor(x*frequency*2)+Math.sin(x*frequency*5), fy=Math.floor(y*frequency*2)+Math.sin(y*frequency*5); r = amplitude * Math.abs(Math.sin(fx)*Math.cos(fy)) * Math.exp(-Math.abs(x*y)*frequency*0.3) * (0.7+0.3*Math.sin(time*6)); break; }
    case "HP_SEM":  { const s1=Math.sin(x*frequency)*Math.cos(y*frequency), s2=Math.sin(x*frequency*3)*Math.cos(y*frequency*3)*0.5, s3=Math.sin(x*frequency*9)*Math.cos(y*frequency*9)*0.25; r = amplitude * (s1+s2+s3) * Math.exp(-time*0.1) * (1+Math.sin(time*10)); break; }
    case "DG_SPECTRAL": { const cx=Math.floor(x*frequency*2), cy=Math.floor(y*frequency*2), cellE=(cx+cy)%2===0?1:-0.5, lx=x*frequency*2-cx, ly=y*frequency*2-cy; r = amplitude * cellE * (2*lx-1)*(2*ly-1) * Math.exp(-Math.sqrt(lx*lx+ly*ly)*frequency) * (0.8+0.2*Math.sin(time*7)); break; }
    default: r = 0;
  }
  if (!isFinite(r)) r = 0;
  return 2 * Math.tanh(r / 2);
}

function buildGeometry(shape: string, density: number): THREE.BufferGeometry {
  const seg = Math.max(8, Math.min(256, density));
  switch (shape) {
    case "sphere":   return new THREE.SphereGeometry(1, seg, seg);
    case "box":      return new THREE.BoxGeometry(1.4, 1.4, 1.4, seg, seg, seg);
    case "torus":    return new THREE.TorusGeometry(0.9, 0.4, Math.max(8, seg/2), seg);
    case "cylinder": return new THREE.CylinderGeometry(0.9, 0.9, 1.8, seg, Math.max(4, seg/2));
    default:         return new THREE.PlaneGeometry(2, 2, seg, seg);
  }
}

function applyDisplacement(geometry: THREE.BufferGeometry, algo: string, params: any): void {
  geometry.computeVertexNormals();
  const pos  = geometry.attributes.position as THREE.BufferAttribute;
  const norm = geometry.attributes.normal   as THREE.BufferAttribute;
  const base = (geometry.userData.basePositions as Float32Array) || (pos.array as Float32Array).slice();
  geometry.userData.basePositions = base;
  for (let i = 0; i < pos.count; i++) {
    const ix = i * 3;
    const bx = base[ix], by = base[ix+1], bz = base[ix+2];
    const h  = calcField(bx, by, bz, algo, params) * params.displacement;
    pos.array[ix]   = bx + norm.array[ix]   * h;
    pos.array[ix+1] = by + norm.array[ix+1] * h;
    pos.array[ix+2] = bz + norm.array[ix+2] * h;
  }
  (pos as any).needsUpdate = true;
  geometry.computeVertexNormals();
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function FractalSkinGenerator() {
  const mountRef    = useRef<HTMLDivElement>(null);
  const stateRef    = useRef<any>({});
  const sessionHash = useRef(generateSessionHash());

  const [panelOpen,    setPanelOpen]    = useState(true);
  const [algo,         setAlgo]         = useState("HERMITE_GAUSS");
  const [shape,        setShape]        = useState("box");
  const [renderMode,   setRenderMode]   = useState("points");
  const [codename,     setCodename]     = useState("");
  const [isRecording,  setIsRecording]  = useState(false);
  const [provenanceCopied, setProvenanceCopied] = useState(false);
  const recorderRef = useRef<MediaRecorder | null>(null);

  const [colors, setColors] = useState({
    front: "#ffffff", back: "#ccd6ff", points: "#00e5cc", background: "#04080f",
  });
  const [params, setParams] = useState({
    frequency: 1.4, amplitude: 4.8, phase: 6.28,
    time: 1.0, meshDensity: 112, displacement: 0.3,
  });

  const colorsRef   = useRef(colors);   colorsRef.current   = colors;
  const codenameRef = useRef(codename); codenameRef.current = codename;
  const paramsRef   = useRef(params);   paramsRef.current   = params;
  const algoRef     = useRef(algo);     algoRef.current     = algo;

  // ── Three.js init ──
  useEffect(() => {
    const mount = mountRef.current!;
    const scene    = new THREE.Scene();
    scene.background = new THREE.Color(0x05060a);
    const camera   = new THREE.PerspectiveCamera(60, mount.clientWidth / mount.clientHeight, 0.1, 100);
    camera.position.set(0, 0.2, 3.2);
    const renderer = new THREE.WebGLRenderer({ antialias: true, preserveDrawingBuffer: true });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.setSize(mount.clientWidth, mount.clientHeight);
    mount.appendChild(renderer.domElement);

    scene.add(new THREE.AmbientLight(0x404040, 0.6));
    const dir = new THREE.DirectionalLight(0xffffff, 1.0); dir.position.set(5, 6, 4); scene.add(dir);
    const rim = new THREE.PointLight(0x00ffff, 0.6);      rim.position.set(-4, -2, 3); scene.add(rim);

    const group = new THREE.Group(); scene.add(group);

    const materialFront  = new THREE.MeshPhysicalMaterial({ color: 0xffffff, metalness: 0.2, roughness: 0.3, clearcoat: 0.5, clearcoatRoughness: 0.15, side: THREE.FrontSide });
    const materialBack   = new THREE.MeshPhysicalMaterial({ color: 0xccd6ff, metalness: 0.3, roughness: 0.45, clearcoat: 0.3, clearcoatRoughness: 0.2,  side: THREE.BackSide  });
    const pointsMaterial = new THREE.PointsMaterial({ color: 0x00e5cc, size: 0.012, sizeAttenuation: true });

    stateRef.current.materials   = { materialFront, materialBack, pointsMaterial, scene };
    stateRef.current.applyColors = () => {
      materialFront.color.set(colorsRef.current.front);
      materialBack.color.set(colorsRef.current.back);
      pointsMaterial.color.set(colorsRef.current.points);
      scene.background = new THREE.Color(colorsRef.current.background);
    };
    stateRef.current.applyColors();

    let mesh: THREE.Mesh | null = null, meshBack: THREE.Mesh | null = null, points: THREE.Points | null = null;

    function rebuild() {
      if (mesh)      { group.remove(mesh);      mesh.geometry.dispose(); }
      if (meshBack)  { group.remove(meshBack);  meshBack.geometry.dispose(); }
      if (points)    { group.remove(points);    points.geometry.dispose(); }

      const geo = buildGeometry(stateRef.current.shape, paramsRef.current.meshDensity);

      if (stateRef.current.renderMode === "points") {
        applyDisplacement(geo, algoRef.current, paramsRef.current);
        points = new THREE.Points(geo, pointsMaterial);
        group.add(points);
      } else if (stateRef.current.renderMode === "wireframe") {
        applyDisplacement(geo, algoRef.current, paramsRef.current);
        materialFront.wireframe = true;
        mesh = new THREE.Mesh(geo, materialFront); group.add(mesh);
      } else {
        materialFront.wireframe = false;
        const geoBack = geo.clone();
        applyDisplacement(geo, algoRef.current, paramsRef.current);
        applyDisplacement(geoBack, algoRef.current, paramsRef.current);
        mesh     = new THREE.Mesh(geo,     materialFront); group.add(mesh);
        meshBack = new THREE.Mesh(geoBack, materialBack);  group.add(meshBack);
      }
    }

    stateRef.current.shape      = shape;
    stateRef.current.renderMode = "points";
    stateRef.current.rebuild    = rebuild;
    stateRef.current.getMeshes  = () => ({ mesh, meshBack, points });
    stateRef.current.renderer   = renderer;
    stateRef.current.scene      = scene;
    stateRef.current.camera     = camera;
    rebuild();

    const ctl = { down: false, lx: 0, ly: 0, rx: 0, ry: 0.4, scale: 1, px: 0, py: 0, pz: 0 };
    const dom = renderer.domElement;
    dom.style.cursor = "grab";
    const onDown  = (e: MouseEvent)  => { ctl.down = true;  ctl.lx = e.clientX; ctl.ly = e.clientY; dom.style.cursor = "grabbing"; };
    const onUp    = ()               => { ctl.down = false; dom.style.cursor = "grab"; };
    const onMove  = (e: MouseEvent)  => { if (!ctl.down) return; ctl.ry += (e.clientX - ctl.lx)*0.01; ctl.rx += (e.clientY - ctl.ly)*0.01; ctl.lx = e.clientX; ctl.ly = e.clientY; };
    const onWheel = (e: WheelEvent)  => { e.preventDefault(); ctl.scale = Math.max(0.2, Math.min(8, ctl.scale * (e.deltaY < 0 ? 1.1 : 0.9))); };
    const onKey   = (e: KeyboardEvent) => {
      const s = 0.1;
      if (e.key==="w"||e.key==="ArrowUp")    ctl.py += s;
      if (e.key==="s"||e.key==="ArrowDown")  ctl.py -= s;
      if (e.key==="a"||e.key==="ArrowLeft")  ctl.px -= s;
      if (e.key==="d"||e.key==="ArrowRight") ctl.px += s;
      if (e.key==="q") ctl.pz += s;
      if (e.key==="e") ctl.pz -= s;
      if (e.key==="r") { ctl.rx=0; ctl.ry=0.4; ctl.scale=1; ctl.px=0; ctl.py=0; ctl.pz=0; }
    };
    dom.addEventListener("mousedown", onDown);
    window.addEventListener("mouseup", onUp);
    window.addEventListener("mousemove", onMove);
    dom.addEventListener("wheel", onWheel, { passive: false });
    window.addEventListener("keydown", onKey);

    let raf: number;
    const animate = () => {
      raf = requestAnimationFrame(animate);
      group.rotation.x = ctl.rx; group.rotation.y = ctl.ry;
      group.scale.setScalar(ctl.scale);
      group.position.set(ctl.px, ctl.py, ctl.pz);
      paramsRef.current.time += 0.016;
      const { mesh: m, meshBack: mb, points: pts } = stateRef.current.getMeshes();
      if (m)   applyDisplacement(m.geometry,   algoRef.current, paramsRef.current);
      if (mb)  applyDisplacement(mb.geometry,  algoRef.current, paramsRef.current);
      if (pts) applyDisplacement(pts.geometry, algoRef.current, paramsRef.current);
      renderer.render(scene, camera);
    };
    animate();

    const ro = new ResizeObserver(() => {
      camera.aspect = mount.clientWidth / mount.clientHeight;
      camera.updateProjectionMatrix();
      renderer.setSize(mount.clientWidth, mount.clientHeight);
    });
    ro.observe(mount);

    return () => {
      cancelAnimationFrame(raf); ro.disconnect();
      dom.removeEventListener("mousedown", onDown); window.removeEventListener("mouseup", onUp);
      window.removeEventListener("mousemove", onMove); dom.removeEventListener("wheel", onWheel);
      window.removeEventListener("keydown", onKey);
      renderer.dispose();
      if (mount.contains(dom)) mount.removeChild(dom);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => { stateRef.current.shape = shape; stateRef.current.renderMode = renderMode; stateRef.current.rebuild?.(); }, [shape, params.meshDensity, renderMode]);
  useEffect(() => { stateRef.current.applyColors?.(); }, [colors]);
  useEffect(() => { stateRef.current.rebuild?.(); }, [algo]);

  const updateParam = useCallback((key: string, value: number) => setParams(p => ({ ...p, [key]: value })), []);

  const randomize = useCallback(() => {
    setShape(SHAPES[Math.floor(Math.random() * SHAPES.length)]);
    setAlgo(ALL_ALGOS[Math.floor(Math.random() * ALL_ALGOS.length)].id);
    setParams(p => ({ ...p, frequency: +(0.3 + Math.random()*6).toFixed(2), amplitude: +(0.3 + Math.random()*3).toFixed(2), phase: +(Math.random()*6.28).toFixed(2), displacement: +(0.1 + Math.random()*1.2).toFixed(2) }));
  }, []);

  // ── Export OBJ — with full provenance header ──
  const exportOBJ = useCallback(() => {
    const geo = buildGeometry(stateRef.current.shape, 64);
    applyDisplacement(geo, algoRef.current, paramsRef.current);
    const pos   = geo.attributes.position as THREE.BufferAttribute;
    const norm  = geo.attributes.normal   as THREE.BufferAttribute;
    const index = geo.index;
    const header = buildProvenanceHeader(algoRef.current, stateRef.current.shape, stateRef.current.renderMode, codenameRef.current, sessionHash.current);
    let obj = header;
    for (let i = 0; i < pos.count; i++) obj += `v ${pos.getX(i).toFixed(5)} ${pos.getY(i).toFixed(5)} ${pos.getZ(i).toFixed(5)}\n`;
    obj += "\n";
    if (stateRef.current.renderMode !== "points") {
      for (let i = 0; i < norm.count; i++) obj += `vn ${norm.getX(i).toFixed(5)} ${norm.getY(i).toFixed(5)} ${norm.getZ(i).toFixed(5)}\n`;
      obj += "\n";
      if (index) {
        for (let i = 0; i < index.count; i += 3) { const a=index.getX(i)+1, b=index.getX(i+1)+1, c=index.getX(i+2)+1; obj += `f ${a}//${a} ${b}//${b} ${c}//${c}\n`; }
      } else {
        for (let i = 0; i < pos.count; i += 3) obj += `f ${i+1}//${i+1} ${i+2}//${i+2} ${i+3}//${i+3}\n`;
      }
    }
    const ext  = stateRef.current.renderMode === "points" ? "_points" : "";
    const blob = new Blob([obj], { type: "text/plain" });
    const url  = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href     = url;
    link.download = `UUON_FractalSkin_${stateRef.current.shape}_${algoRef.current}${ext}_${sessionHash.current}.obj`;
    document.body.appendChild(link); link.click(); document.body.removeChild(link);
    URL.revokeObjectURL(url); geo.dispose();
  }, []);

  // ── Export PNG — with LSB steganographic provenance stamp ──
  const exportPNG = useCallback(() => {
    const dom = stateRef.current.renderer?.domElement as HTMLCanvasElement;
    if (!dom) return;
    stampCanvasProvenance(dom, sessionHash.current);
    dom.toBlob((blob) => {
      if (!blob) return;
      const url  = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href     = url;
      link.download = `UUON_FractalSkin_${stateRef.current.shape}_${algoRef.current}_${sessionHash.current}.png`;
      document.body.appendChild(link); link.click(); document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, "image/png");
  }, []);

  // ── Record WebM ──
  const toggleRecording = useCallback(() => {
    const dom = stateRef.current.renderer?.domElement as HTMLCanvasElement;
    if (!dom) return;
    if (isRecording) { recorderRef.current?.stop(); return; }
    if (typeof (dom as any).captureStream !== "function" || typeof window.MediaRecorder === "undefined") {
      alert("Video capture not supported here. Try Chrome, or use Export PNG."); return;
    }
    try {
      const stream = (dom as any).captureStream(30);
      const mimeType = ["video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"].find(m => MediaRecorder.isTypeSupported(m)) || "video/webm";
      const recorder = new MediaRecorder(stream, { mimeType });
      const chunks: Blob[] = [];
      recorder.ondataavailable = (e) => { if (e.data.size > 0) chunks.push(e.data); };
      recorder.onstop = () => {
        const blob = new Blob(chunks, { type: mimeType });
        const url  = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href     = url;
        link.download = `UUON_FractalSkin_${stateRef.current.shape}_${algoRef.current}_${sessionHash.current}.webm`;
        document.body.appendChild(link); link.click(); document.body.removeChild(link);
        URL.revokeObjectURL(url); setIsRecording(false);
      };
      recorder.start(); recorderRef.current = recorder; setIsRecording(true);
    } catch (err) { console.error("Recording failed:", err); alert("Recording failed. Try Chrome."); }
  }, [isRecording]);

  const copyProvenance = useCallback(() => {
    navigator.clipboard.writeText(sessionHash.current).then(() => {
      setProvenanceCopied(true); setTimeout(() => setProvenanceCopied(false), 2000);
    });
  }, []);

  const activeAlgo = ALL_ALGOS.find(a => a.id === algo);

  return (
    <div style={{ position: "relative", width: "100%", height: "680px", background: "#04080f", borderRadius: 8, overflow: "hidden", fontFamily: "'Share Tech Mono', monospace", display: "flex", flexDirection: "column" }}>
      <div style={{ display: "flex", width: "100%", flex: 1, minHeight: 0 }}>

        {/* ── Canvas ── */}
        <div ref={mountRef} style={{ flex: 1, minWidth: 0, height: "100%" }} />

        {/* ── Control Panel ── */}
        <div style={{ width: panelOpen ? 300 : 0, transition: "width 0.2s ease", height: "100%", background: "rgba(10,12,18,0.95)", borderLeft: panelOpen ? "1px solid rgba(0,255,255,0.25)" : "none", overflowY: "auto", color: "#fff", flexShrink: 0 }}>
          {panelOpen && (
            <div style={{ padding: 16 }}>

              <h3 style={sectionHead}>SHAPE</h3>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6, marginBottom: 10 }}>
                {SHAPES.map(s => <button key={s} onClick={() => setShape(s)} style={btnStyle(shape === s, false)}>{s}</button>)}
              </div>

              <button onClick={randomize} style={{ width: "100%", marginBottom: 8, padding: "8px", background: "linear-gradient(45deg,#7b5ea7,#00e5cc)", border: "none", color: "#04080f", fontWeight: "bold", borderRadius: 5, cursor: "pointer", fontSize: 12 }}>🎲 Randomize</button>

              <h3 style={sectionHead}>RENDER MODE</h3>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 6, marginBottom: 10 }}>
                {["solid","wireframe","points"].map(m => <button key={m} onClick={() => setRenderMode(m)} style={btnStyle(renderMode === m, false)}>{m}</button>)}
              </div>

              <h3 style={sectionHead}>VISUAL CONTROLS</h3>
              <ColorRow label="Front"      value={colors.front}      onChange={v => setColors(c => ({ ...c, front: v }))} />
              <ColorRow label="Back"       value={colors.back}       onChange={v => setColors(c => ({ ...c, back: v }))} />
              <ColorRow label="Points"     value={colors.points}     onChange={v => setColors(c => ({ ...c, points: v }))} />
              <ColorRow label="Background" value={colors.background} onChange={v => setColors(c => ({ ...c, background: v }))} />
              <div style={{ display: "flex", gap: 6, marginBottom: 14 }}>
                {[{name:"void",c:"#04080f"},{name:"teal",c:"#00e5cc"},{name:"gold",c:"#c9a84c"},{name:"violet",c:"#7b5ea7"}].map(sw => (
                  <button key={sw.name} title={sw.name} onClick={() => setColors(c => ({ ...c, points: sw.c }))} style={{ width: 22, height: 22, borderRadius: 4, border: "1px solid rgba(255,255,255,0.3)", background: sw.c, cursor: "pointer" }} />
                ))}
                <span style={{ fontSize: 10, color: "#9aa", alignSelf: "center" }}>brand palette</span>
              </div>

              <h3 style={sectionHead}>CODENAME</h3>
              <input type="text" value={codename} onChange={e => setCodename(e.target.value)} placeholder="enter codename" style={{ width: "100%", marginBottom: 16, padding: "6px 8px", background: "rgba(255,255,255,0.05)", border: "1px solid #00e5cc", color: "#00e5cc", borderRadius: 4, fontSize: 12, fontFamily: "inherit", boxSizing: "border-box" }} />

              {/* ── Provenance Token ── */}
              <div style={{ marginBottom: 16, padding: 10, background: "rgba(201,168,76,0.08)", border: "1px solid rgba(201,168,76,0.3)", borderRadius: 6 }}>
                <div style={{ fontSize: 10, color: "#c9a84c", letterSpacing: 1, marginBottom: 4 }}>SESSION PROVENANCE TOKEN</div>
                <div style={{ fontSize: 9, color: "#fff", wordBreak: "break-all", marginBottom: 6 }}>{sessionHash.current}</div>
                <button onClick={copyProvenance} style={{ width: "100%", padding: "4px", background: provenanceCopied ? "rgba(0,229,204,0.2)" : "rgba(201,168,76,0.15)", border: "1px solid #c9a84c", color: "#c9a84c", borderRadius: 4, cursor: "pointer", fontSize: 10 }}>
                  {provenanceCopied ? "✓ Copied" : "Copy Token"}
                </button>
              </div>

              <button onClick={exportOBJ} style={{ width: "100%", marginBottom: 8, padding: "8px", background: "linear-gradient(45deg,#ff8a3d,#c9a84c)", border: "none", color: "#04080f", fontWeight: "bold", borderRadius: 5, cursor: "pointer", fontSize: 12 }}>⬇ Export OBJ (3D + provenance)</button>
              <button onClick={exportPNG} style={{ width: "100%", marginBottom: 8, padding: "8px", background: "rgba(0,229,204,0.15)", border: "1px solid #00e5cc", color: "#00e5cc", fontWeight: "bold", borderRadius: 5, cursor: "pointer", fontSize: 12 }}>📷 Export PNG (watermarked)</button>
              <button onClick={toggleRecording} style={{ width: "100%", marginBottom: 16, padding: "8px", background: isRecording ? "#c0392b" : "rgba(255,138,61,0.15)", border: `1px solid ${isRecording ? "#c0392b" : "#ff8a3d"}`, color: isRecording ? "#fff" : "#ff8a3d", fontWeight: "bold", borderRadius: 5, cursor: "pointer", fontSize: 12 }}>
                {isRecording ? "■ Stop & Save Video (.webm)" : "🎥 Record Animation (.webm)"}
              </button>

              <h3 style={sectionHead}>EM ALGORITHMS</h3>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6, marginBottom: 16 }}>
                {EM_ALGORITHMS.map(a => <button key={a.id} onClick={() => setAlgo(a.id)} style={btnStyle(algo === a.id, false)}>{a.label}</button>)}
              </div>

              <h3 style={{ ...sectionHead, color: "#ff8a3d" }}>SEM BURN / ENERGY</h3>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6, marginBottom: 16 }}>
                {SEM_ALGORITHMS.map(a => <button key={a.id} onClick={() => setAlgo(a.id)} style={btnStyle(algo === a.id, true)}>{a.label}</button>)}
              </div>

              <h3 style={sectionHead}>PARAMETERS</h3>
              <Slider label="Frequency"    min={0.1} max={10}  step={0.1}  value={params.frequency}    onChange={v => updateParam("frequency", v)} />
              <Slider label="Amplitude"    min={0.1} max={5}   step={0.1}  value={params.amplitude}    onChange={v => updateParam("amplitude", v)} />
              <Slider label="Phase"        min={0}   max={6.28} step={0.1} value={params.phase}        onChange={v => updateParam("phase", v)} />
              <Slider label="Mesh Density" min={16}  max={224} step={8}    value={params.meshDensity}  onChange={v => updateParam("meshDensity", v)} />
              <Slider label="Displacement" min={0}   max={2}   step={0.05} value={params.displacement} onChange={v => updateParam("displacement", v)} />

              <div style={{ marginTop: 16, padding: 10, background: "rgba(0,255,255,0.06)", borderRadius: 6, fontSize: 11, lineHeight: 1.4, color: "#cdd" }}>
                <strong style={{ color: "#ff8a3d" }}>{activeAlgo?.label}</strong>
                <div style={{ marginTop: 4 }}>{activeAlgo?.info}</div>
              </div>

              <div style={{ marginTop: 14, fontSize: 11, color: "#9aa", lineHeight: 1.5 }}>Drag: rotate · Scroll: zoom · WASD: move · Q/E: dolly · R: reset</div>
            </div>
          )}
        </div>
      </div>

      {/* Panel toggle */}
      <button onClick={() => setPanelOpen(o => !o)} style={{ position: "absolute", top: 10, right: panelOpen ? 312 : 10, transition: "right 0.2s ease", background: "rgba(0,229,204,0.15)", border: "1px solid #00e5cc", color: "#00e5cc", borderRadius: 4, padding: "4px 8px", fontSize: 11, cursor: "pointer" }}>
        {panelOpen ? "Hide Panel ▶" : "◀ Show Panel"}
      </button>

      {/* Footer */}
      <div style={{ flexShrink: 0, borderTop: "1px solid rgba(201,168,76,0.35)", background: "#04080f", color: "#7B5EA7", fontSize: 10.5, padding: "8px 16px", display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 8 }}>
        <div style={{ color: "#C9A84C", letterSpacing: 0.5 }}>©LOUUD — UUON Foundation Inc. 2026{codename ? ` · ${codename}` : ""}</div>
        <div style={{ color: "#00E5CC" }}>{stateRef.current.shape || shape} · {activeAlgo?.label} · {renderMode} · density {params.meshDensity}</div>
        <div style={{ color: "#7b5ea7", fontSize: 9 }}>{sessionHash.current}</div>
      </div>
    </div>
  );
}

// ─── Sub-components ───────────────────────────────────────────────────────────

const sectionHead: React.CSSProperties = { color: "#00e5cc", fontSize: 13, letterSpacing: 1, marginBottom: 8, marginTop: 4 };

function btnStyle(active: boolean, sem: boolean): React.CSSProperties {
  return { background: active ? (sem ? "rgba(255,138,61,0.3)" : "rgba(0,229,204,0.3)") : "rgba(255,255,255,0.05)", border: `1px solid ${sem ? "#ff8a3d" : "#00e5cc"}`, color: sem ? "#ff8a3d" : "#00e5cc", borderRadius: 5, padding: "6px 6px", fontSize: 10, cursor: "pointer" };
}

function ColorRow({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) {
  return (
    <div style={{ display: "flex", alignItems: "center", marginBottom: 6, gap: 8 }}>
      <label style={{ minWidth: 80, fontSize: 11, color: "#ccc" }}>{label}</label>
      <input type="color" value={value} onChange={e => onChange(e.target.value)} style={{ width: 36, height: 22, border: "1px solid rgba(255,255,255,0.2)", borderRadius: 4, background: "none", padding: 0, cursor: "pointer" }} />
      <span style={{ fontSize: 10, color: "#9aa" }}>{value}</span>
    </div>
  );
}

function Slider({ label, min, max, step, value, onChange }: { label: string; min: number; max: number; step: number; value: number; onChange: (v: number) => void }) {
  return (
    <div style={{ display: "flex", alignItems: "center", marginBottom: 8, gap: 8 }}>
      <label style={{ minWidth: 90, fontSize: 11, color: "#ccc" }}>{label}</label>
      <input type="range" min={min} max={max} step={step} value={value} onChange={e => onChange(parseFloat(e.target.value))} style={{ flex: 1 }} />
      <span style={{ minWidth: 36, fontSize: 11, color: "#00e5cc", textAlign: "right" }}>{Math.round(value * 100) / 100}</span>
    </div>
  );
}
