import { useState, useRef, useCallback } from 'react';
import { Button } from './ui/button';
import { Label } from './ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Switch } from './ui/switch';
import { Camera, Video, Square, Image, Film, Shield, Lock, Package } from 'lucide-react';
import JSZip from 'jszip';

interface MediaExportPanelProps {
  canvasRef?: HTMLCanvasElement | null;
  getCanvas?: () => HTMLCanvasElement | null;
  shapeName?: string;
}

async function generateSHA256Hash(data: ArrayBuffer): Promise<string> {
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

function generateExportFingerprint(): string {
  const entropy = [
    Date.now().toString(36),
    Math.random().toString(36).slice(2),
    navigator.userAgent.slice(-10)
  ].join('-');
  return btoa(entropy).slice(0, 16);
}

interface SecurityManifest {
  exportId: string;
  shapeName: string;
  hash: string;
  fingerprint: string;
  timestamp: string;
  format: string;
  resolution: string;
  protectionLayers: string[];
  attribution: {
    creator: string;
    organization: string;
    copyright: string;
    license: string;
  };
  verification: {
    algorithm: string;
    blockchainReady: boolean;
    integrityCode: string;
  };
}

function createSecurityManifest(
  shapeName: string,
  hash: string,
  fingerprint: string,
  timestamp: string,
  format: string,
  resolution: string
): SecurityManifest {
  return {
    exportId: `DMENSION-${Date.now().toString(36).toUpperCase()}`,
    shapeName,
    hash,
    fingerprint,
    timestamp,
    format,
    resolution,
    protectionLayers: [
      'SHA-256 Cryptographic Hash',
      'Digital Fingerprint (Session-Based)',
      'Timestamp Verification (ISO 8601)',
      'Attribution Tracking',
      'Blockchain-Ready Hash'
    ],
    attribution: {
      creator: 'Phillip Aguiar Ruiz III',
      organization: 'UUON Foundation',
      copyright: `© ${new Date().getFullYear()} UUON Foundation. Created by Phillip Aguiar Ruiz III. All Rights Reserved.`,
      license: 'Commercial with Attribution Required'
    },
    verification: {
      algorithm: 'SHA-256',
      blockchainReady: true,
      integrityCode: hash.slice(0, 32)
    }
  };
}

async function downloadSecurePackage(
  mediaBlob: Blob,
  mediaFilename: string,
  manifest: SecurityManifest
): Promise<void> {
  const zip = new JSZip();
  
  zip.file(mediaFilename, mediaBlob);
  
  const manifestJson = JSON.stringify(manifest, null, 2);
  zip.file('verification.json', manifestJson);
  
  const readme = `# Secure Export Package
  
## Export ID: ${manifest.exportId}
## Created: ${manifest.timestamp}

### Verification Information
- **Hash Algorithm**: ${manifest.verification.algorithm}
- **Integrity Code**: ${manifest.verification.integrityCode}
- **Blockchain Ready**: ${manifest.verification.blockchainReady ? 'Yes' : 'No'}

### Attribution
- **Creator**: ${manifest.attribution.creator}
- **Organization**: ${manifest.attribution.organization}
- **Copyright**: ${manifest.attribution.copyright}
- **License**: ${manifest.attribution.license}

### Protection Layers
${manifest.protectionLayers.map(p => `- ${p}`).join('\n')}

### How to Verify
1. Calculate SHA-256 hash of the media file
2. Compare with the hash in verification.json
3. If hashes match, the file is authentic and unmodified

---
Generated by Dmension Mathematical Universe
© ${new Date().getFullYear()} UUON Foundation. Created by Phillip Aguiar Ruiz III. All Rights Reserved.
`;
  
  zip.file('README.md', readme);
  
  const zipBlob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
  const url = URL.createObjectURL(zipBlob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${manifest.shapeName}_secure_${manifest.exportId}.zip`;
  link.click();
  URL.revokeObjectURL(url);
  
  console.log(`📦 Secure package downloaded: ${manifest.exportId}`);
}

function downloadManifest(manifest: SecurityManifest, filename: string): void {
  const manifestJson = JSON.stringify(manifest, null, 2);
  const blob = new Blob([manifestJson], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

async function embedSecurityMetadata(
  canvas: HTMLCanvasElement, 
  shapeName: string,
  format: string,
  resolution: string
): Promise<{ dataUrl: string; hash: string; fingerprint: string; timestamp: string; manifest: SecurityManifest }> {
  const timestamp = new Date().toISOString();
  const fingerprint = generateExportFingerprint();
  
  const dataUrl = canvas.toDataURL(`image/${format === 'jpg' ? 'jpeg' : format}`);
  
  const response = await fetch(dataUrl);
  const blob = await response.blob();
  const arrayBuffer = await blob.arrayBuffer();
  const hash = await generateSHA256Hash(arrayBuffer);
  
  const manifest = createSecurityManifest(shapeName, hash, fingerprint, timestamp, format, resolution);
  
  console.log(`🔒 Security manifest created:`, manifest);
  
  return { dataUrl, hash, fingerprint, timestamp, manifest };
}

export default function MediaExportPanel({ canvasRef, getCanvas, shapeName = 'shape' }: MediaExportPanelProps) {
  const [imageFormat, setImageFormat] = useState<'png' | 'jpg' | 'webp'>('png');
  const [imageQuality, setImageQuality] = useState<number>(0.95);
  const [imageResolution, setImageResolution] = useState<'1x' | '2x' | '4x' | '8k'>('2x');
  const [includeBackground, setIncludeBackground] = useState(true);
  const [securityEnabled, setSecurityEnabled] = useState(true);
  const [lastExportHash, setLastExportHash] = useState<string | null>(null);
  
  const [isRecording, setIsRecording] = useState(false);
  const [recordingTime, setRecordingTime] = useState(0);
  const [videoDuration, setVideoDuration] = useState<number>(5);
  const [videoFps, setVideoFps] = useState<number>(30);
  
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const recordedChunksRef = useRef<Blob[]>([]);
  const recordingIntervalRef = useRef<NodeJS.Timeout | null>(null);
  const animationFrameRef = useRef<number | null>(null);
  
  const getCanvasElement = useCallback(() => {
    if (canvasRef) return canvasRef;
    if (getCanvas) return getCanvas();
    const canvas = document.querySelector('canvas');
    return canvas as HTMLCanvasElement | null;
  }, [canvasRef, getCanvas]);

  const captureScreenshot = useCallback(async () => {
    const canvas = getCanvasElement();
    if (!canvas) {
      console.error('No canvas found for screenshot');
      return;
    }

    try {
      const scale = imageResolution === '1x' ? 1 : imageResolution === '2x' ? 2 : imageResolution === '4x' ? 4 : 8;
      const width = canvas.width * scale;
      const height = canvas.height * scale;
      
      const offscreenCanvas = document.createElement('canvas');
      offscreenCanvas.width = width;
      offscreenCanvas.height = height;
      const ctx = offscreenCanvas.getContext('2d');
      
      if (!ctx) return;
      
      if (!includeBackground) {
        ctx.clearRect(0, 0, width, height);
      }
      
      ctx.imageSmoothingEnabled = true;
      ctx.imageSmoothingQuality = 'high';
      ctx.drawImage(canvas, 0, 0, width, height);
      
      const timestamp = new Date().toISOString().slice(0, 19).replace(/[:-]/g, '');
      const filename = `${shapeName}_${timestamp}.${imageFormat}`;
      
      if (securityEnabled) {
        const securityData = await embedSecurityMetadata(offscreenCanvas, shapeName, imageFormat, imageResolution);
        setLastExportHash(securityData.hash.slice(0, 16));
        
        const response = await fetch(securityData.dataUrl);
        const mediaBlob = await response.blob();
        
        await downloadSecurePackage(mediaBlob, filename, securityData.manifest);
        
        console.log(`🛡️ ENTERPRISE SECURITY APPLIED - Atomic package:`, {
          exportId: securityData.manifest.exportId,
          hash: securityData.hash.slice(0, 32) + '...',
          protectionLevel: 'ENTERPRISE-GRADE',
          contents: ['media file', 'verification.json', 'README.md']
        });
      } else {
        const mimeType = imageFormat === 'png' ? 'image/png' : 
                         imageFormat === 'jpg' ? 'image/jpeg' : 'image/webp';
        const quality = imageFormat === 'png' ? undefined : imageQuality;
        const dataUrl = offscreenCanvas.toDataURL(mimeType, quality);
        
        const link = document.createElement('a');
        link.download = filename;
        link.href = dataUrl;
        link.click();
      }
      
      console.log(`📸 Screenshot saved: ${filename} ${securityEnabled ? '(Protected + Manifest)' : ''}`);
    } catch (error) {
      console.error('Screenshot capture failed:', error);
    }
  }, [getCanvasElement, imageFormat, imageQuality, imageResolution, includeBackground, shapeName, securityEnabled]);

  const startRecording = useCallback(async () => {
    const canvas = getCanvasElement();
    if (!canvas) {
      console.error('No canvas found for video recording');
      return;
    }

    try {
      recordedChunksRef.current = [];
      
      const stream = canvas.captureStream(videoFps);
      const mimeType = 'video/webm;codecs=vp9';
      
      if (!MediaRecorder.isTypeSupported(mimeType)) {
        console.warn('VP9 not supported, falling back to VP8');
      }
      
      const mediaRecorder = new MediaRecorder(stream, {
        mimeType: MediaRecorder.isTypeSupported(mimeType) ? mimeType : 'video/webm',
        videoBitsPerSecond: 8000000
      });
      
      mediaRecorder.ondataavailable = (event) => {
        if (event.data.size > 0) {
          recordedChunksRef.current.push(event.data);
        }
      };
      
      mediaRecorder.onstop = async () => {
        const blob = new Blob(recordedChunksRef.current, { type: 'video/webm' });
        const timestamp = new Date().toISOString().slice(0, 19).replace(/[:-]/g, '');
        const videoFilename = `${shapeName}_${timestamp}.webm`;
        
        if (securityEnabled) {
          const arrayBuffer = await blob.arrayBuffer();
          const hash = await generateSHA256Hash(arrayBuffer);
          const fingerprint = generateExportFingerprint();
          setLastExportHash(hash.slice(0, 16));
          
          const manifest = createSecurityManifest(
            shapeName, 
            hash, 
            fingerprint, 
            new Date().toISOString(), 
            'webm', 
            `${videoDuration}s @ ${videoFps}fps`
          );
          
          await downloadSecurePackage(blob, videoFilename, manifest);
          
          console.log(`🛡️ VIDEO SECURITY APPLIED - Atomic package:`, {
            exportId: manifest.exportId,
            hash: hash.slice(0, 32) + '...',
            protectionLevel: 'ENTERPRISE-GRADE',
            contents: ['video file', 'verification.json', 'README.md']
          });
        } else {
          const url = URL.createObjectURL(blob);
          const link = document.createElement('a');
          link.download = videoFilename;
          link.href = url;
          link.click();
          URL.revokeObjectURL(url);
        }
        
        console.log(`🎬 Video saved: ${videoFilename} ${securityEnabled ? '(Secure Package)' : ''}`);
      };
      
      mediaRecorderRef.current = mediaRecorder;
      mediaRecorder.start(100);
      setIsRecording(true);
      setRecordingTime(0);
      
      recordingIntervalRef.current = setInterval(() => {
        setRecordingTime(prev => {
          const newTime = prev + 1;
          if (newTime >= videoDuration) {
            stopRecording();
          }
          return newTime;
        });
      }, 1000);
      
      console.log(`🎬 Recording started (${videoDuration}s @ ${videoFps}fps)`);
    } catch (error) {
      console.error('Video recording failed:', error);
      setIsRecording(false);
    }
  }, [getCanvasElement, videoFps, videoDuration, shapeName, securityEnabled]);

  const stopRecording = useCallback(() => {
    if (mediaRecorderRef.current && mediaRecorderRef.current.state !== 'inactive') {
      mediaRecorderRef.current.stop();
    }
    
    if (recordingIntervalRef.current) {
      clearInterval(recordingIntervalRef.current);
      recordingIntervalRef.current = null;
    }
    
    if (animationFrameRef.current) {
      cancelAnimationFrame(animationFrameRef.current);
      animationFrameRef.current = null;
    }
    
    setIsRecording(false);
    setRecordingTime(0);
  }, []);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  return (
    <div className="space-y-4 p-3 bg-gray-900/60 rounded-lg border border-cyan-500/30">
      <div className="flex items-center gap-2">
        <Camera className="w-4 h-4 text-cyan-400" />
        <h3 className="text-sm font-semibold text-cyan-400 uppercase tracking-wide">Media Export</h3>
        {securityEnabled && (
          <div className="ml-auto flex items-center gap-1 text-green-400">
            <Shield className="w-3 h-3" />
            <span className="text-[9px]">Protected</span>
          </div>
        )}
      </div>

      <div className="space-y-2 p-2 bg-green-900/20 rounded border border-green-500/30">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-xs text-green-300">
            <Lock className="w-3 h-3" />
            <span className="font-medium">Security Protection</span>
          </div>
          <Switch
            checked={securityEnabled}
            onCheckedChange={setSecurityEnabled}
            className="scale-75"
          />
        </div>
        {securityEnabled && (
          <div className="text-[9px] text-green-400/80 space-y-0.5">
            <p>SHA-256 Hash | Digital Fingerprint | Timestamp</p>
            {lastExportHash && (
              <p className="font-mono text-green-300">Last: {lastExportHash}...</p>
            )}
          </div>
        )}
      </div>

      <div className="space-y-3 p-2 bg-gray-800/50 rounded border border-cyan-500/20">
        <div className="flex items-center gap-2 text-xs text-cyan-300">
          <Image className="w-3 h-3" />
          <span className="font-medium">Screenshot</span>
        </div>
        
        <div className="grid grid-cols-2 gap-2">
          <div>
            <Label className="text-[10px] text-cyan-300">Format</Label>
            <Select value={imageFormat} onValueChange={(v) => setImageFormat(v as typeof imageFormat)}>
              <SelectTrigger className="h-7 text-xs bg-gray-800 border-cyan-500/30">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="bg-gray-800 border-cyan-500/30">
                <SelectItem value="png">PNG (Lossless)</SelectItem>
                <SelectItem value="jpg">JPG (Smaller)</SelectItem>
                <SelectItem value="webp">WebP (Modern)</SelectItem>
              </SelectContent>
            </Select>
          </div>
          
          <div>
            <Label className="text-[10px] text-cyan-300">Resolution</Label>
            <Select value={imageResolution} onValueChange={(v) => setImageResolution(v as typeof imageResolution)}>
              <SelectTrigger className="h-7 text-xs bg-gray-800 border-cyan-500/30">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="bg-gray-800 border-cyan-500/30">
                <SelectItem value="1x">1x (Standard)</SelectItem>
                <SelectItem value="2x">2x (HD)</SelectItem>
                <SelectItem value="4x">4x (4K Ultra HD)</SelectItem>
                <SelectItem value="8k">8x (8K Cinema)</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-1">
            <Switch
              checked={includeBackground}
              onCheckedChange={setIncludeBackground}
              className="scale-75"
            />
            <Label className="text-[10px] text-cyan-300">Include Background</Label>
          </div>
          
          <Button
            onClick={captureScreenshot}
            size="sm"
            className="h-7 text-xs bg-cyan-600 hover:bg-cyan-500"
          >
            <Camera className="w-3 h-3 mr-1" />
            Capture
          </Button>
        </div>
      </div>

      <div className="space-y-3 p-2 bg-gray-800/50 rounded border border-pink-500/20">
        <div className="flex items-center gap-2 text-xs text-pink-300">
          <Film className="w-3 h-3" />
          <span className="font-medium">Video Recording</span>
          {isRecording && (
            <span className="ml-auto text-red-400 animate-pulse flex items-center gap-1">
              <span className="w-2 h-2 bg-red-500 rounded-full" />
              {formatTime(recordingTime)} / {formatTime(videoDuration)}
            </span>
          )}
        </div>
        
        <div className="grid grid-cols-2 gap-2">
          <div>
            <Label className="text-[10px] text-pink-300">Duration</Label>
            <Select 
              value={videoDuration.toString()} 
              onValueChange={(v) => setVideoDuration(parseInt(v))}
              disabled={isRecording}
            >
              <SelectTrigger className="h-7 text-xs bg-gray-800 border-pink-500/30">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="bg-gray-800 border-pink-500/30">
                <SelectItem value="3">3 seconds</SelectItem>
                <SelectItem value="5">5 seconds</SelectItem>
                <SelectItem value="10">10 seconds</SelectItem>
                <SelectItem value="15">15 seconds</SelectItem>
                <SelectItem value="30">30 seconds</SelectItem>
                <SelectItem value="60">60 seconds</SelectItem>
              </SelectContent>
            </Select>
          </div>
          
          <div>
            <Label className="text-[10px] text-pink-300">Frame Rate</Label>
            <Select 
              value={videoFps.toString()} 
              onValueChange={(v) => setVideoFps(parseInt(v))}
              disabled={isRecording}
            >
              <SelectTrigger className="h-7 text-xs bg-gray-800 border-pink-500/30">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="bg-gray-800 border-pink-500/30">
                <SelectItem value="24">24 fps (Film)</SelectItem>
                <SelectItem value="30">30 fps (Standard)</SelectItem>
                <SelectItem value="60">60 fps (Smooth)</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        
        <div className="flex justify-end">
          {isRecording ? (
            <Button
              onClick={stopRecording}
              size="sm"
              className="h-7 text-xs bg-red-600 hover:bg-red-500"
            >
              <Square className="w-3 h-3 mr-1" />
              Stop Recording
            </Button>
          ) : (
            <Button
              onClick={startRecording}
              size="sm"
              className="h-7 text-xs bg-pink-600 hover:bg-pink-500"
            >
              <Video className="w-3 h-3 mr-1" />
              Start Recording
            </Button>
          )}
        </div>
      </div>

      <div className="text-[9px] text-gray-400 space-y-1">
        <p>📸 Screenshots capture the current view at selected resolution</p>
        <p>🎬 Videos record shape animations as WebM files</p>
        {securityEnabled && <p>🛡️ All exports include enterprise-grade security protection</p>}
      </div>
    </div>
  );
}
