import React, { useState, useEffect, useRef, useMemo } from 'react';
import { Search, X, ChevronUp, ChevronDown, Sparkles, BookOpen, ChevronRight } from 'lucide-react';
import { SurfaceParameters } from '../types/math';
import { SHAPE_CATEGORIES } from '../lib/shapeCategories';
import { getDefaultParameters } from '../lib/parametricSurfacesClean';
import { generatePieceOfPi, cosmicWeight, multiBaseExpression, COSMIC_CONSTANTS } from '../lib/perspectiveMathematicsEngine';
import { highlightScientificKeywords, getKeywordClass } from '../lib/scientificKeywordHighlighter';
import { getShapeSummary } from '../lib/dynamicShapeSummary';

const HighlightedText: React.FC<{ text: string }> = ({ text }) => {
  const { segments } = highlightScientificKeywords(text);
  return (
    <>
      {segments.map((segment, idx) => (
        segment.isKeyword ? (
          <span key={idx} className={getKeywordClass()}>{segment.text}</span>
        ) : (
          <span key={idx}>{segment.text}</span>
        )
      ))}
    </>
  );
};

interface ShapeSummary {
  origin: string;
  function: string;
  applications: string;
  future: string;
}

const SHAPE_SUMMARIES: Record<string, ShapeSummary> = {
  sphere: {
    origin: "The sphere has been studied since ancient Greece. Euclid's Elements (300 BCE) explored its properties, while Archimedes calculated its volume and surface area. The term derives from Greek 'sphaira' meaning ball.",
    function: "A sphere is defined as all points equidistant from a center point. This perfect symmetry makes it the most efficient shape for enclosing volume with minimal surface area - nature's default container.",
    applications: "Spheres appear everywhere: planetary bodies, soap bubbles, ball bearings, radar domes, pressure vessels, and cell membranes. In physics, the Bloch sphere represents quantum states.",
    future: "Hyperspheres extend into 4D+ dimensions for AI embeddings, quantum computing state spaces, and neural network latent spaces. Spherical harmonics enable climate modeling and brain imaging."
  },
  torus: {
    origin: "Latin for 'cushion' or 'knot', the torus gained mathematical prominence in the 19th century. Riemann studied its topology, revealing it has genus-1 (one hole) making it fundamentally different from a sphere.",
    function: "A torus is generated by rotating a circle around an axis in its plane. Its topology allows paths that loop around differently - critical for understanding magnetic confinement and wormhole physics.",
    applications: "Tokamak fusion reactors use toroidal geometry to contain plasma. Doughnut-shaped antennas, tire inner tubes, and architectural domes all exploit torus properties. In cryptography, elliptic curves live on tori.",
    future: "Toroidal computing architectures promise efficient parallel processing. Quantum error correction uses toric codes. The shape may describe the universe's actual geometry - a cosmic doughnut."
  },
  mobius_strip: {
    origin: "Discovered independently by August Möbius and Johann Listing in 1858. This surface has only one side and one edge - walking along it returns you upside-down. A true mathematical paradox made physical.",
    function: "The Möbius strip is non-orientable, meaning you cannot consistently define inside vs outside. It has half the boundary of a regular strip but the same area - topology defying intuition.",
    applications: "Industrial conveyor belts use Möbius design to wear evenly on both 'sides'. Recording tape, printer ribbons, and electronic resistors exploit this property. The universal recycling symbol is a Möbius strip.",
    future: "Möbius metamaterials enable unique electromagnetic properties. Molecular Möbius rings could revolutionize drug delivery. Topological computing may use Möbius-like quantum states for robust qubits."
  },
  klein_bottle: {
    origin: "Felix Klein conceived this surface in 1882 as a non-orientable closed surface. It cannot exist in 3D without self-intersection - a true 4D object that challenges our spatial intuition.",
    function: "The Klein bottle has no inside or outside - imagine a bottle whose neck curves through itself to join its base from inside. It's the 3D boundary of a 4D solid, like how a sphere bounds a ball.",
    applications: "Klein bottles appear in theoretical physics, topology research, and art. They model certain quantum field configurations and help mathematicians understand higher-dimensional spaces.",
    future: "4D printing may eventually create true Klein bottles. Virtual reality already renders them. Understanding Klein topology informs M-theory string compactification and quantum gravity research."
  },
  dna_double_helix: {
    origin: "Watson and Crick's 1953 discovery, built on Rosalind Franklin's X-ray crystallography, revealed life's blueprint. The double helix structure explained heredity and launched molecular biology.",
    function: "Two antiparallel strands wind around each other with base pairs (A-T, G-C) forming rungs. The helix pitch is 3.4nm with 10.5 base pairs per turn. This geometry enables replication and repair.",
    applications: "DNA structure guides CRISPR gene editing, forensic identification, ancestry tracing, and synthetic biology. Understanding the helix enables drug design targeting specific genetic sequences.",
    future: "DNA data storage could hold humanity's knowledge in a few grams. Origami DNA creates nanomachines. Artificial DNA with extended alphabets may enable new life forms and computing paradigms."
  },
  mandelbulb: {
    origin: "Daniel White and Paul Nylander created the Mandelbulb in 2009 as a true 3D extension of the Mandelbrot set. Earlier 3D attempts failed to capture the infinite complexity of the 2D original.",
    function: "The Mandelbulb uses spherical coordinates with power-8 iteration: (r,θ,φ)→(r^n, n·θ, n·φ). Points escaping to infinity are outside; bounded points reveal the intricate fractal boundary.",
    applications: "Mandelbulbs generate stunning procedural terrain, alien landscapes in films, and video game environments. They help visualize chaotic systems and demonstrate self-similarity across scales.",
    future: "Real-time fractal rendering enables infinite virtual worlds. Mandelbulb variations may model biological growth patterns. Quantum fractals could describe multi-scale physics phenomena."
  },
  lorenz_attractor: {
    origin: "Edward Lorenz discovered this chaotic system in 1963 while modeling weather. The famous 'butterfly effect' - where small changes cause large consequences - comes from this research.",
    function: "Three coupled differential equations create a system that never repeats but stays bounded within a butterfly-shaped region. Two lobes represent competing atmospheric convection states.",
    applications: "The Lorenz attractor demonstrates why weather prediction has fundamental limits. It appears in laser physics, chemical reactions, and economic models. Artists use it for generative design.",
    future: "Machine learning on chaotic systems may improve predictions. Lorenz dynamics inspire reservoir computing - a new AI paradigm. Understanding attractors guides climate modeling under global change."
  },
  hypercube: {
    origin: "Charles Howard Hinton coined 'tesseract' in 1888 for the 4D cube. Salvador Dalí's 1954 'Corpus Hypercubus' famously depicted Christ crucified on an unfolded tesseract.",
    function: "A hypercube has 16 vertices, 32 edges, 24 square faces, and 8 cubic cells. Each vertex connects to 4 perpendicular edges - impossible in 3D but natural in 4D. Rotations reveal hidden symmetries.",
    applications: "Tesseracts visualize high-dimensional data in machine learning. They structure hypercube interconnection networks in supercomputers. String theory uses hypercubic lattices for calculations.",
    future: "4D spatial reasoning may become standard in physics and AI. Tesseract projections help train neural networks on geometric reasoning. Quantum hypercubes could enable new error-correcting codes."
  },
  calabi_yau_manifold: {
    origin: "Eugenio Calabi conjectured (1954) and Shing-Tung Yau proved (1977) these special 6D shapes exist. They became central to string theory's attempt to unify physics.",
    function: "Calabi-Yau manifolds are Ricci-flat Kähler manifolds with vanishing first Chern class. In string theory, 6 extra spatial dimensions may curl into these shapes at every point in space.",
    applications: "These manifolds determine which particles and forces exist in our universe. Their topology influences particle masses and coupling constants. Mathematicians study them for pure geometry.",
    future: "Finding the 'right' Calabi-Yau could explain why physics has its observed parameters. AI now searches vast Calabi-Yau databases. Their geometry may reveal deep connections between math and physics."
  },
  schwarzschild_metric_spacetime: {
    origin: "Karl Schwarzschild found this exact solution to Einstein's equations in 1916 while serving in WWI trenches. It describes spacetime around non-rotating black holes - the simplest gravitational system.",
    function: "The metric shows how time slows and space warps near mass. At the Schwarzschild radius rs=2GM/c², even light cannot escape. This defines the event horizon - the point of no return.",
    applications: "GPS satellites correct for Schwarzschild time dilation (microseconds/day matter). Gravitational lensing bends starlight. LIGO detects merging black holes described by this geometry.",
    future: "Black hole imaging (Event Horizon Telescope) tests Schwarzschild predictions. Hawking radiation from the metric's quantum effects remains unobserved. Understanding may unify gravity and quantum mechanics."
  },
  riemann_curvature_surface: {
    origin: "Bernhard Riemann introduced intrinsic curvature in 1854, revolutionizing geometry. His tensor measures how much parallel transport around a loop rotates a vector - pure geometry independent of embedding.",
    function: "The Riemann tensor R^l_ijk has 20 independent components in 4D. It encodes how geodesics deviate, directly relating to gravitational tidal forces in general relativity.",
    applications: "General relativity is written using Riemann curvature. GPS, gravitational wave detection, and black hole physics all require these calculations. Medical imaging uses related differential geometry.",
    future: "Quantum gravity may quantize Riemann curvature. AI learns differential geometry for robotics navigation. Understanding curvature flow guides topology and could solve remaining Millennium Problems."
  },
  default: {
    origin: "This mathematical form emerges from the rich history of geometry, physics, and natural pattern discovery spanning from ancient civilizations to modern computational mathematics.",
    function: "The shape is defined by parametric equations that map 2D parameters (u,v) to 3D coordinates (x,y,z). These equations encode geometric properties, symmetries, and topological characteristics.",
    applications: "Mathematical surfaces find use in scientific visualization, computer graphics, engineering design, educational demonstrations, and artistic expression across many fields.",
    future: "Advances in computing, 3D printing, and virtual reality continue to expand applications. AI-driven mathematical discovery may reveal new surface families with unexpected properties."
  }
};

interface ShapeFormulaBarProps {
  parameters: SurfaceParameters;
  onShapeSelect: (params: Partial<SurfaceParameters>) => void;
  onMeshDensityChange?: (uSegments: number, vSegments: number) => void;
}

const SHAPE_FORMULAS: Record<string, { formula: string; description: string }> = {
  // Core shapes - UUON Foundation Signatures
  uuon: { formula: 'f(u,v) = u² · n, O(n) linear complexity', description: 'U²O(n) Linear Complexity Algorithm - UUON\'s core mathematical identity' },
  sphere: { formula: 'x = a·sin(φ)·cos(θ), y = b·sin(φ)·sin(θ), z = c·cos(φ)', description: 'Spherical parametric surface' },
  cube: { formula: 'Vertices at (±a, ±b, ±c)', description: 'Hexahedron with square faces' },
  torus: { formula: 'x = (R+r·cos(v))·cos(u), y = (R+r·cos(v))·sin(u), z = r·sin(v)', description: 'Doughnut surface of revolution' },
  cylinder: { formula: 'x = r·cos(θ), y = r·sin(θ), z = h·t', description: 'Circular cylinder' },
  cone: { formula: 'x = r·(1-t)·cos(θ), y = r·(1-t)·sin(θ), z = h·t', description: 'Circular cone' },
  ellipsoid: { formula: 'x²/a² + y²/b² + z²/c² = 1', description: 'Stretched sphere' },
  pyramid: { formula: 'Base: square, apex at (0,h,0)', description: 'Square pyramid' },
  tetrahedron: { formula: '4 vertices: equidistant in 3D space', description: 'Platonic solid, 4 faces' },
  octahedron: { formula: '|x| + |y| + |z| = r', description: 'Platonic solid, 8 faces' },
  dodecahedron: { formula: '12 pentagonal faces, φ-based vertices', description: 'Platonic solid, golden ratio' },
  icosahedron: { formula: '20 triangular faces, 12 vertices', description: 'Platonic solid' },
  
  // 4D Hyperdimensional
  hypersphere: { formula: 'x² + y² + z² + w² = r²', description: '4D sphere projection' },
  hypercube: { formula: 'Tesseract vertices at (±1, ±1, ±1, ±1)', description: '4D cube projection' },
  tesseract: { formula: '8 cubic cells, 16 vertices, 32 edges', description: '4-dimensional hypercube' },
  hyperoctahedron: { formula: '16-cell: 16 tetrahedra, 8 vertices', description: '4D cross-polytope' },
  '24_cell': { formula: '24 octahedral cells, self-dual in 4D', description: 'Unique 4D regular polytope' },
  '120_cell': { formula: '120 dodecahedral cells, 600 vertices', description: 'Largest regular 4D polytope' },
  '600_cell': { formula: '600 tetrahedral cells, 120 vertices', description: '4D analogue of icosahedron' },
  
  // Topology
  mobius_strip: { formula: 'x = (1+u/2·cos(v/2))·cos(v), y = (1+u/2·cos(v/2))·sin(v), z = u/2·sin(v/2)', description: 'Non-orientable surface' },
  klein_bottle: { formula: 'Immersion: ℝ² → ℝ⁴ → ℝ³', description: 'Non-orientable closed surface' },
  trefoil_knot: { formula: 'x = sin(t)+2·sin(2t), y = cos(t)-2·cos(2t), z = -sin(3t)', description: 'Torus knot (2,3)' },
  figure_eight_knot: { formula: 'x = (2+cos(2t))cos(3t), y = (2+cos(2t))sin(3t), z = sin(4t)', description: 'Alternating knot 4₁' },
  hopf_fibration: { formula: 'S³ → S², fiber = S¹', description: 'Principal circle bundle' },
  
  // Fractals
  mandelbrot_3d: { formula: 'zₙ₊₁ = zₙ² + c, |z| < 2', description: 'Fractal escape-time set' },
  mandelbulb: { formula: 'zₙ₊₁ = zₙⁿ + c in spherical coords', description: '3D Mandelbrot analogue' },
  julia_set_3d: { formula: 'zₙ₊₁ = zₙ² + c, c fixed', description: '3D Julia fractal' },
  sierpinski_tetrahedron: { formula: 'IFS: 4 contractions to vertices', description: 'Self-similar fractal' },
  menger_sponge: { formula: 'Hausdorff dim = log(20)/log(3) ≈ 2.73', description: '3D Sierpinski carpet' },
  koch_snowflake_3d: { formula: 'Recursive edge trisection + extrusion', description: '3D Koch surface' },
  
  // Attractors
  lorenz_attractor: { formula: 'dx/dt = σ(y-x), dy/dt = x(ρ-z)-y, dz/dt = xy-βz', description: 'Chaotic attractor' },
  rossler_attractor: { formula: 'dx/dt = -y-z, dy/dt = x+ay, dz/dt = b+z(x-c)', description: 'Spiral chaos' },
  chen_attractor: { formula: 'dx/dt = a(y-x), dy/dt = (c-a)x-xz+cy, dz/dt = xy-bz', description: 'Chen system' },
  aizawa_attractor: { formula: 'Multi-scroll chaotic system', description: 'Multi-wing attractor' },
  thomas_attractor: { formula: 'dx/dt = sin(y)-bx, cyclic permutations', description: 'Cyclically symmetric' },
  
  // Diatoms (Biomimetic Silica Architecture - 200+ million years of engineering)
  radial_centric_diatom: { formula: 'r(u,v) = v·a·(1+d·sin(c·θ))·(1+f·sin(e·v·20π)), z = b·(1-r²)', description: 'Circular frustule with radial costae and annular striae (Coscinodiscus-type)' },
  pennate_diatom: { formula: 'Ellipse: s²/a² + t²/b² < 1, z = c·(1-bound)·striae·raphe', description: 'Boat-shaped bilateral diatom with transverse striae and raphe (Navicula-type)' },
  polygonal_diatom: { formula: 'n-gon: θ = 2πu, r = v·a/cos(π/n), areolae = sin(d·r·π)·cos(d·θ·3)', description: 'Triangular/pentagonal/hexagonal form with areolae pore networks' },
  colonial_chain_diatom: { formula: 'Chain: cells = floor(c), spacing = 2a + d, spines connect frustules', description: 'Linked frustule units with silica spines (Chaetoceros-type)' },
  stellate_diatom: { formula: 'Star: r = a + (b-a)·v·exp(-|θ-arm|·n/2), n-fold arms', description: 'Star-shaped with radiating arms for nutrient uptake (Asterionella-type)' },
  diatom_frustule_complete: { formula: 'Full 3D: epitheca + hypotheca + girdle bands, costae + areolae', description: 'Complete silica shell with both overlapping valves' },
  coscinodiscus_diatom: { formula: 'Disc: hexagonal areolae in concentric rings, dome = b·(1-r²)', description: 'Classic disc diatom with hexagonal pore pattern' },
  navicula_diatom: { formula: 'Navicular: |s|^2.5 + |t·a/b|^2.5 < 1, raphe groove at t=0', description: 'Archetypal boat-shaped pennate ("little ship" in Latin)' },
  triceratium_diatom: { formula: 'Triangle: r = a·(1+0.2·cos(3θ)), horns at 0°, 120°, 240°', description: 'Three-cornered with elevated horn processes at vertices' },
  arachnoidiscus_diatom: { formula: 'Web: radial = |sin(cθ/2)|, concentric = |sin(d·v·π)|', description: 'Spider-web patterned with radial + concentric silica ribbing' },

  // Biological
  dna_double_helix: { formula: 'x = r·cos(θ), y = r·sin(θ), z = p·θ/2π (B-DNA: 10.5bp/turn)', description: 'Watson-Crick double helix' },
  dna_geometric_code: { formula: 'TAD loops + φ harmonics + epigenetic states', description: '3D structural memory system' },
  a_dna_helix: { formula: 'A-form: 11bp/turn, 2.8nm pitch, 20° tilt', description: 'Dehydrated DNA form' },
  z_dna_helix: { formula: 'Z-form: 12bp/turn, left-handed, zigzag', description: 'Left-handed DNA helix' },
  mitochondria: { formula: 'ΔG = ΔG° + RT·ln(Q), cristae fold area', description: 'Cellular ATP production' },
  atp_synthase: { formula: 'ADP + Pi → ATP, F₀F₁ rotary motor', description: 'Molecular turbine enzyme' },
  kinesin: { formula: '8nm steps, ATP hydrolysis → walking motion', description: 'Motor protein on microtubules' },
  ribosome_detailed: { formula: 'mRNA + tRNA → polypeptide chain', description: 'Protein synthesis machine' },
  proteasome: { formula: 'Ubiquitin tag → protein degradation', description: 'Cellular protein recycler' },
  cell_membrane: { formula: 'Phospholipid bilayer: 5-10nm thick', description: 'Fluid mosaic model' },
  virus_capsid: { formula: 'T-number = h² + hk + k² symmetry', description: 'Icosahedral protein shell' },
  
  // Atomic & Quantum
  hydrogen_1s_orbital: { formula: 'ψ₁ₛ = (1/√π)(1/a₀)^(3/2)·e^(-r/a₀)', description: 'Ground state wavefunction' },
  hydrogen_2p_orbital: { formula: 'ψ₂ₚ ∝ r·e^(-r/2a₀)·Y₁ᵐ(θ,φ)', description: 'First excited orbital' },
  hydrogen_3d_orbital: { formula: 'ψ₃ᵈ ∝ r²·e^(-r/3a₀)·Y₂ᵐ(θ,φ)', description: 'D-orbital wavefunction' },
  electron_cloud: { formula: '|ψ|² probability density', description: 'Quantum probability distribution' },
  qubit_bloch_sphere: { formula: '|ψ⟩ = cos(θ/2)|0⟩ + e^(iφ)sin(θ/2)|1⟩', description: 'Quantum state representation' },
  
  // Cosmology & Physics
  shape_of_universe: { formula: 'Σᵢ ψᵢ(θ,φ,r,t) · Φᵢ(cosmic,quantum,lattice)', description: 'Unified mathematical structure' },
  einstein_field_equations: { formula: 'Gμν + Λgμν = (8πG/c⁴)Tμν', description: 'Spacetime curvature = energy-momentum' },
  schwarzschild_metric_spacetime: { formula: 'ds² = -(1-rs/r)dt² + (1-rs/r)⁻¹dr² + r²dΩ²', description: 'Static black hole metric' },
  kerr_rotating_black_hole: { formula: 'ds² with Σ = r² + a²cos²θ, Δ = r² - rsr + a²', description: 'Rotating black hole spacetime' },
  wheeler_dewitt_equation: { formula: 'Ĥ|Ψ⟩ = 0 (Quantum cosmology constraint)', description: 'Wave function of universe' },
  ads_cft_correspondence: { formula: 'Z_CFT[φ₀] = Z_gravity[φ→φ₀]', description: 'Holographic principle duality' },
  gravitational_wave: { formula: 'h = (2G/c⁴)(1/r)(d²Q/dt²)', description: 'Spacetime ripple amplitude' },
  loop_quantum_area_spectrum: { formula: 'A = 8πγℓₚ² Σⱼ √(j(j+1))', description: 'Quantized area eigenvalues' },
  spin_network_vertex: { formula: 'Intertwiner: ⊗ᵢVⱼᵢ → ℂ', description: 'LQG graph node' },
  calabi_yau_manifold: { formula: 'Ricci-flat Kähler, c₁ = 0', description: 'String theory compactification' },
  
  // Electromagnetic & Wave
  maxwell_equations: { formula: '∇·E = ρ/ε₀, ∇×E = -∂B/∂t, ∇·B = 0, ∇×B = μ₀J + μ₀ε₀∂E/∂t', description: 'Electromagnetic field equations' },
  yang_mills_field: { formula: 'Dμ Fμν = Jν, Fμν = ∂μAν - ∂νAμ + g[Aμ,Aν]', description: 'Non-abelian gauge field' },
  dirac_equation: { formula: '(iγμ∂μ - m)ψ = 0', description: 'Relativistic electron equation' },
  klein_gordon_equation: { formula: '(∂² + m²)φ = 0', description: 'Relativistic scalar field' },
  schrodinger_time_dependent: { formula: 'iℏ∂ψ/∂t = Ĥψ', description: 'Quantum evolution equation' },
  schrodinger_time_independent: { formula: 'Ĥψ = Eψ', description: 'Stationary state equation' },
  navier_stokes_turbulence: { formula: 'ρ(∂v/∂t + v·∇v) = -∇p + μ∇²v + f', description: 'Fluid dynamics equations' },
  
  // Cryptography
  aes_rijndael_cipher: { formula: 'C = SubBytes∘ShiftRows∘MixColumns∘AddRoundKey(P)', description: 'Symmetric block cipher' },
  sha256_compression_function: { formula: 'H(m) = IV + Σᵢ compress(mᵢ)', description: 'Cryptographic hash function' },
  elliptic_curve_cryptography: { formula: 'y² = x³ + ax + b (mod p), P + Q = R', description: 'ECDSA/ECDH curves' },
  keccak_sha3_sponge: { formula: 'Absorb: S ⊕ Pi, Squeeze: extract(S)', description: 'Sponge construction hash' },
  lattice_kyber_ntru: { formula: 'LWE: b = As + e (mod q)', description: 'Post-quantum cryptography' },
  rsa_modular_exponentiation: { formula: 'C = M^e mod n, M = C^d mod n', description: 'Public key cryptosystem' },
  diffie_hellman_key_exchange: { formula: 'K = g^(ab) mod p', description: 'Key agreement protocol' },
  merkle_tree: { formula: 'H(H(a)||H(b)) = parent hash', description: 'Hash tree structure' },
  
  // Riemann Geometry (Riemann 1854) - Foundation of Modern Physics & Differential Geometry
  riemann_curvature_surface: { formula: 'R^l_ijk = dΓ^l_jk/dx^i - dΓ^l_ik/dx^j + Γ^m_jk·Γ^l_im - Γ^m_ik·Γ^l_jm', description: 'Riemann curvature tensor (1854). Measures intrinsic curvature of space. Foundation of General Relativity, GPS satellite corrections, gravitational wave detection.' },
  ricci_curvature_surface: { formula: 'R_ij = R^k_ikj = g^kl·R_likj', description: 'Ricci tensor (Ricci-Curbastro 1887). Contracts Riemann tensor to describe volume distortion. Used in Einstein field equations, cosmology, black hole physics.' },
  scalar_curvature_surface: { formula: 'R = g^ij·R_ij', description: 'Scalar curvature - single number measuring total curvature. Applications: cosmological constant, dark energy models, universe geometry classification.' },
  christoffel_symbols_surface: { formula: 'Γ^k_ij = ½g^kl(∂g_jl/∂x^i + ∂g_il/∂x^j - ∂g_ij/∂x^l)', description: 'Connection coefficients (Christoffel 1869). Encode how vectors change along curved paths. Essential for spacecraft navigation, tensor calculus, machine learning on manifolds.' },
  metric_tensor_riemann: { formula: 'ds² = g_ij·dx^i·dx^j', description: 'Riemannian metric tensor (1854). Defines distance and angles in curved space. Foundation of all spacetime physics, computer graphics, medical imaging.' },
  geodesic_flow_surface: { formula: 'd²x^k/dt² + Γ^k_ij·(dx^i/dt)(dx^j/dt) = 0', description: 'Geodesic equation - shortest paths in curved space. Applications: GPS routing, light bending near stars, optimal control theory, robotics path planning.' },
  parallel_transport_surface: { formula: 'DV^k/dt = dV^k/dt + Γ^k_ij·(dx^i/dt)V^j = 0', description: 'Parallel transport (Levi-Civita 1917). Moving vectors without rotation on curved surfaces. Used in inertial navigation, fiber optics, quantum computing geometric phases.' },
  exponential_map_surface: { formula: 'exp_p: T_pM → M, exp_p(v) = γ_v(1)', description: 'Exponential map - projects tangent vectors onto manifold. Applications: Lie group theory, robotics kinematics, statistical manifolds, neural network optimization.' },
  sectional_curvature_surface: { formula: 'K(σ) = R(X,Y,Y,X) / (g(X,X)g(Y,Y) - g(X,Y)²)', description: 'Sectional curvature - Gaussian curvature of 2D slices. Classifies spaces: positive (spheres), zero (flat), negative (hyperbolic). Used in topology, cosmology.' },
  weyl_tensor_surface: { formula: 'C_ijkl = R_ijkl - Schouten terms', description: 'Weyl conformal tensor (Weyl 1918). Measures tidal forces and gravitational waves independent of matter. Essential for gravitational wave astronomy, LIGO analysis.' },
  laplace_beltrami_surface: { formula: 'Δf = (1/√det(g))·∂_i(√det(g)·g^ij·∂_j f)', description: 'Laplace-Beltrami operator - generalized Laplacian on curved surfaces. Applications: heat diffusion, spectral geometry, shape analysis, machine learning on graphs.' },
  covariant_derivative_surface: { formula: '∇_i V^k = ∂V^k/∂x^i + Γ^k_ij·V^j', description: 'Covariant derivative - differentiation that respects curved geometry. Foundation of gauge theory, particle physics, General Relativity field equations.' },
  volume_form_surface: { formula: 'dV = √det(g)·dx^1 ∧ ... ∧ dx^n', description: 'Riemannian volume form - measures volume in curved space. Applications: integration on manifolds, probability distributions, cosmological volume calculations.' },
  square_root_riemann: { formula: 'w = √z = √ρ·e^(iθ/2), two-sheeted', description: 'Square root Riemann surface (1851). Multi-valued complex function visualization. Applications: branch cut theory, complex analysis, quantum mechanics phase.' },
  logarithm_riemann: { formula: 'w = ln(z) = ln|z| + i·arg(z) + 2πik', description: 'Logarithm Riemann surface - infinite sheets spiraling. Foundation of complex analysis, signal processing, control theory stability analysis.' },
  exponential_riemann: { formula: 'w = e^z = e^x·(cos(y) + i·sin(y))', description: 'Complex exponential surface. Euler formula visualization. Applications: Fourier analysis, quantum mechanics, electrical engineering AC circuits.' },
  nth_root_riemann: { formula: 'w = z^(1/n), n-sheeted surface', description: 'Nth root Riemann surface - n sheets connected at origin. Applications: algebraic geometry, string theory moduli spaces, cryptographic elliptic curves.' },
  elliptic_function: { formula: 'sn(u), cn(u), dn(u) doubly periodic', description: 'Jacobi elliptic functions - generalize trig functions. Applications: pendulum motion, conformal mapping, soliton theory, cryptography.' },

  // Mathematical functions
  riemann_zeta_function: { formula: 'ζ(s) = Σₙ₌₁^∞ n⁻ˢ = Πₚ(1-p⁻ˢ)⁻¹', description: 'Prime distribution analytic continuation' },
  fibonacci_spiral: { formula: 'Fₙ = Fₙ₋₁ + Fₙ₋₂, r = φⁿ', description: 'Golden ratio spiral' },
  prime_spiral_ulam: { formula: 'Primes on integer spiral → diagonal patterns', description: 'Prime distribution visualization' },
  fourier_transform_surface: { formula: 'F(ω) = ∫f(t)e^(-iωt)dt', description: 'Time-frequency decomposition' },
  laplace_transform_surface: { formula: 'F(s) = ∫₀^∞ f(t)e^(-st)dt', description: 'Complex frequency analysis' },
  euler_product_formula: { formula: 'ζ(s) = Πₚ(1-p⁻ˢ)⁻¹', description: 'Prime-zeta connection' },
  gamma_function_surface: { formula: 'Γ(z) = ∫₀^∞ t^(z-1)e^(-t)dt', description: 'Generalized factorial' },
  beta_function_surface: { formula: 'B(x,y) = Γ(x)Γ(y)/Γ(x+y)', description: 'Euler integral' },
  
  // Quantum Computing
  grover_search_algorithm: { formula: 'O(√N) oracle queries for N items', description: 'Quantum search speedup' },
  shor_factorization_algorithm: { formula: 'O((log N)³) factoring via QFT', description: 'Quantum integer factorization' },
  quantum_fourier_transform: { formula: 'QFT|j⟩ = 1/√N Σₖ e^(2πijk/N)|k⟩', description: 'Quantum frequency domain' },
  hadamard_gate: { formula: 'H = 1/√2 [[1,1],[1,-1]]', description: 'Superposition creation' },
  cnot_gate: { formula: '|a,b⟩ → |a, a⊕b⟩', description: 'Controlled NOT gate' },
  
  // Fast Multipole & Algorithms
  fast_multipole_001: { formula: 'Φ(r) = Σ (qᵢ/|r-rᵢ|) via multipole expansion', description: 'O(N) N-body algorithm' },
  fast_multipole_method: { formula: 'Far-field: multipole, Near-field: direct', description: 'Hierarchical decomposition' },
  barnes_hut_tree: { formula: 'Octree decomposition, θ threshold', description: 'O(N log N) approximation' },
  fft_butterfly: { formula: 'Xₖ = Σₙ xₙ·e^(-2πikn/N)', description: 'Cooley-Tukey radix-2' },
  
  // Minimal surfaces
  catenoid: { formula: 'x = c·cosh(z/c)·cos(θ)', description: 'Minimal surface of revolution' },
  helicoid: { formula: 'x = r·cos(θ), y = r·sin(θ), z = c·θ', description: 'Ruled minimal surface' },
  enneper_surface: { formula: 'x = u-u³/3+uv², y = v-v³/3+u²v, z = u²-v²', description: 'Self-intersecting minimal' },
  scherk_surface: { formula: 'sin(z) = sinh(x)sinh(y)', description: 'Doubly periodic minimal' },
  costa_surface: { formula: 'Weierstrass representation on torus', description: 'Embedded genus-1 minimal' },
  
  // Anatomy
  heart_shape: { formula: '(x² + y² + z² - 1)³ - x²z³ - y²z³/10 = 0', description: 'Cardiac geometry' },
  brain_cortex: { formula: 'Gyrification index, sulcal depth map', description: 'Neural surface folding' },
  lung_bronchial_tree: { formula: 'Fractal branching: d^n ratio', description: 'Respiratory fractal' },
  eye_cornea: { formula: 'Aspherical: z = cr²/(1+√(1-(1+k)c²r²))', description: 'Optical surface' },
  bone_trabecular: { formula: 'Percolation lattice, porosity ε', description: 'Spongy bone structure' },
  
  // Surfaces
  roman_surface: { formula: 'x²y² + y²z² + z²x² + xyz = 0', description: 'Steiner surface' },
  boys_surface: { formula: 'Immersion of RP² in ℝ³', description: 'Non-orientable immersion' },
  cross_cap: { formula: 'x = sin(u)sin(2v)/2, y = sin(2u)cos²(v), z = cos(2u)cos²(v)', description: 'Projective plane model' },
  dini_surface: { formula: 'x = a·cos(u)sin(v), y = a·sin(u)sin(v), z = a(cos(v)+ln(tan(v/2)))+bu', description: 'Pseudosphere helix' },
  pseudosphere: { formula: 'K = -1/a² constant negative curvature', description: 'Tractricoid revolution' },
  
  // Seashells & Nature
  seashell: { formula: 'r = ae^(bθ), exponential spiral + growth', description: 'Logarithmic spiral shell' },
  nautilus_shell: { formula: 'r = ae^(bθ), b ≈ 0.18', description: 'Golden ratio approximation' },
  sunflower_phyllotaxis: { formula: 'θₙ = n·137.5°, rₙ = c√n', description: 'Fibonacci angle pattern' },
  
  // Set Theory
  venn_diagram_3: { formula: 'A ∩ B ∩ C, 8 regions', description: '3-set intersection' },
  cantor_set_3d: { formula: 'Remove middle thirds recursively', description: 'Uncountable measure-zero' },
  power_set_lattice: { formula: 'P(S) = 2^|S| elements', description: 'Subset ordering' },
  
  // Entropy & Information
  shannon_entropy: { formula: 'H = -Σ p(x)log₂p(x)', description: 'Information content' },
  boltzmann_entropy: { formula: 'S = kB·ln(Ω)', description: 'Statistical mechanics' },
  von_neumann_entropy: { formula: 'S = -Tr(ρ·ln(ρ))', description: 'Quantum information' }
};

function getShapeFormula(shapeType: string): { formula: string; description: string } {
  if (SHAPE_FORMULAS[shapeType]) {
    return SHAPE_FORMULAS[shapeType];
  }
  
  // Generate formula based on shape naming patterns
  const cleanName = shapeType.replace(/_/g, ' ');
  const titleName = cleanName.charAt(0).toUpperCase() + cleanName.slice(1);
  
  // Pattern-based formula generation for validation
  const lowerType = shapeType.toLowerCase();
  
  // Quantum patterns
  if (lowerType.includes('qubit') || lowerType.includes('quantum')) {
    return { formula: '|ψ⟩ = α|0⟩ + β|1⟩, |α|² + |β|² = 1', description: `Quantum ${titleName}` };
  }
  if (lowerType.includes('entangle')) {
    return { formula: '|Φ⁺⟩ = (1/√2)(|00⟩ + |11⟩)', description: `Entanglement ${titleName}` };
  }
  if (lowerType.includes('superposition')) {
    return { formula: 'Ψ = Σᵢ cᵢ|ψᵢ⟩', description: `Superposition ${titleName}` };
  }
  
  // Cryptographic patterns
  if (lowerType.includes('hash') || lowerType.includes('sha')) {
    return { formula: 'H(m) = compress(IV ⊕ mᵢ)', description: `Cryptographic ${titleName}` };
  }
  if (lowerType.includes('encrypt') || lowerType.includes('cipher') || lowerType.includes('aes')) {
    return { formula: 'C = Eₖ(P), P = Dₖ(C)', description: `Encryption ${titleName}` };
  }
  if (lowerType.includes('lattice') || lowerType.includes('kyber')) {
    return { formula: 'b = As + e (mod q)', description: `Post-quantum ${titleName}` };
  }
  
  // Biological patterns
  if (lowerType.includes('dna') || lowerType.includes('helix')) {
    return { formula: 'r(θ) = a·e^(bθ), pitch = 3.4nm', description: `Molecular ${titleName}` };
  }
  if (lowerType.includes('protein') || lowerType.includes('amino')) {
    return { formula: 'φ, ψ Ramachandran angles', description: `Biochemical ${titleName}` };
  }
  if (lowerType.includes('cell') || lowerType.includes('membrane')) {
    return { formula: 'Lipid bilayer: 5-10nm', description: `Cellular ${titleName}` };
  }
  
  // Physics patterns
  if (lowerType.includes('field') || lowerType.includes('maxwell')) {
    return { formula: '∇·E = ρ/ε₀, ∇×B = μ₀J', description: `Field theory ${titleName}` };
  }
  if (lowerType.includes('wave') || lowerType.includes('oscillat')) {
    return { formula: 'ψ(x,t) = A·sin(kx - ωt)', description: `Wave ${titleName}` };
  }
  if (lowerType.includes('gravity') || lowerType.includes('schwarzschild')) {
    return { formula: 'ds² = -(1-rₛ/r)dt² + dr²/(1-rₛ/r)', description: `Gravitational ${titleName}` };
  }
  if (lowerType.includes('spacetime') || lowerType.includes('metric')) {
    return { formula: 'Gμν = 8πG/c⁴ Tμν', description: `Relativistic ${titleName}` };
  }
  
  // Fractal patterns
  if (lowerType.includes('mandel') || lowerType.includes('julia')) {
    return { formula: 'zₙ₊₁ = zₙ² + c, |z| < 2', description: `Fractal ${titleName}` };
  }
  if (lowerType.includes('sierpinski') || lowerType.includes('koch')) {
    return { formula: 'IFS: T(x) = Σᵢ wᵢTᵢ(x)', description: `Fractal ${titleName}` };
  }
  
  // Attractor patterns  
  if (lowerType.includes('lorenz') || lowerType.includes('attractor')) {
    return { formula: 'dx/dt = σ(y-x), dy/dt = x(ρ-z)-y', description: `Chaotic ${titleName}` };
  }
  
  // Topological patterns
  if (lowerType.includes('mobius') || lowerType.includes('klein')) {
    return { formula: 'Non-orientable: χ = V - E + F', description: `Topological ${titleName}` };
  }
  if (lowerType.includes('torus') || lowerType.includes('toroid')) {
    return { formula: 'x = (R+r·cos(v))·cos(u)', description: `Toroidal ${titleName}` };
  }
  if (lowerType.includes('knot') || lowerType.includes('link')) {
    return { formula: 'Torus knot T(p,q)', description: `Knot theory ${titleName}` };
  }
  
  // 4D patterns
  if (lowerType.includes('hyper') || lowerType.includes('4d') || lowerType.includes('tesseract')) {
    return { formula: 'x² + y² + z² + w² = r²', description: `4D ${titleName}` };
  }
  if (lowerType.includes('polytope') || lowerType.includes('_cell')) {
    return { formula: 'n-polytope projection: ℝⁿ → ℝ³', description: `Polytope ${titleName}` };
  }
  
  // Algorithm patterns
  if (lowerType.includes('algorithm') || lowerType.includes('sort') || lowerType.includes('search')) {
    return { formula: 'O(n log n) complexity', description: `Algorithm ${titleName}` };
  }
  if (lowerType.includes('fft') || lowerType.includes('fourier')) {
    return { formula: 'F(ω) = ∫f(t)e^(-iωt)dt', description: `Transform ${titleName}` };
  }
  
  // Mathematical patterns
  if (lowerType.includes('spiral') || lowerType.includes('golden')) {
    return { formula: 'r = a·φⁿ, φ = 1.618...', description: `Golden ratio ${titleName}` };
  }
  if (lowerType.includes('fibonacci') || lowerType.includes('phi')) {
    return { formula: 'Fₙ = Fₙ₋₁ + Fₙ₋₂', description: `Fibonacci ${titleName}` };
  }
  if (lowerType.includes('prime') || lowerType.includes('zeta')) {
    return { formula: 'ζ(s) = Σₙ₌₁^∞ n⁻ˢ', description: `Number theory ${titleName}` };
  }
  
  // Surface patterns
  if (lowerType.includes('surface') || lowerType.includes('manifold')) {
    return { formula: 'S: ℝ² → ℝ³, (u,v) ↦ (x,y,z)', description: `Parametric ${titleName}` };
  }
  if (lowerType.includes('minimal') || lowerType.includes('catenoid')) {
    return { formula: 'H = 0 (mean curvature)', description: `Minimal ${titleName}` };
  }
  
  // Modular patterns
  if (lowerType.includes('mod_') || lowerType.includes('modulo') || lowerType.includes('modular')) {
    return { formula: 'f(x) ≡ g(x) (mod n)', description: `Modular ${titleName}` };
  }
  
  // Default: generate parametric formula
  return { 
    formula: `(u,v) → [x(u,v), y(u,v), z(u,v)]`,
    description: titleName
  };
}

function getShapeDisplayName(shape: string): string {
  return shape
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

export default function ShapeFormulaBar({ parameters, onShapeSelect, onMeshDensityChange }: ShapeFormulaBarProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const [showDropdown, setShowDropdown] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);
  const [showSummary, setShowSummary] = useState(false);
  const searchRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  
  const { formula: currentFormula, description: currentDescription } = getShapeFormula(parameters.type);
  
  const shapeSummary = useMemo(() => {
    return getShapeSummary(parameters.type, SHAPE_SUMMARIES, currentFormula, currentDescription);
  }, [parameters.type, currentFormula, currentDescription]);

  const allShapes = useMemo(() => {
    return SHAPE_CATEGORIES.flatMap(cat => cat.shapes);
  }, []);

  const filteredShapes = useMemo(() => {
    if (!searchQuery.trim()) return [];
    const query = searchQuery.toLowerCase();
    return allShapes
      .filter(shape => shape.toLowerCase().includes(query) || 
                       getShapeDisplayName(shape).toLowerCase().includes(query))
      .slice(0, 10);
  }, [searchQuery, allShapes]);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (searchRef.current && !searchRef.current.contains(event.target as Node)) {
        setShowDropdown(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleShapeSelect = (shape: string) => {
    const defaults = getDefaultParameters(shape);
    onShapeSelect({ ...defaults, type: shape as any });
    setSearchQuery('');
    setShowDropdown(false);
  };

  const shapeName = getShapeDisplayName(parameters.type);
  const formula = currentFormula;
  const description = currentDescription;
  
  const pieceOfPi = useMemo(() => {
    return generatePieceOfPi(parameters.type, {
      a: parameters.a,
      b: parameters.b,
      c: parameters.c,
      d: parameters.d,
      e: parameters.e,
      f: parameters.f
    });
  }, [parameters.type, parameters.a, parameters.b, parameters.c, parameters.d, parameters.e, parameters.f]);
  
  const cosmicLink = useMemo(() => {
    const combinedValue = parameters.a + parameters.b * COSMIC_CONSTANTS.PHI + parameters.c * COSMIC_CONSTANTS.PI;
    return cosmicWeight(combinedValue);
  }, [parameters.a, parameters.b, parameters.c]);

  return (
    <div className="absolute bottom-3 left-1/2 transform -translate-x-1/2 z-40 flex items-center gap-2">
      {isExpanded ? (
        <div className="bg-slate-800 rounded-lg border border-cyan-500/50 shadow-2xl transition-all duration-200">
          <div className="flex items-center gap-3 px-4 py-2.5">
            <button
              onClick={() => setIsExpanded(false)}
              className="p-1 hover:bg-slate-700 rounded transition-colors"
              title="Collapse"
            >
              <ChevronDown className="w-4 h-4 text-cyan-400" />
            </button>
            <div className="flex-shrink-0">
              <div className="text-[9px] text-cyan-400 font-semibold uppercase tracking-wide">Shape Formula</div>
              <div className="text-cyan-300 font-bold text-sm">{shapeName}</div>
            </div>
            <div className="h-10 w-px bg-cyan-500/40" />
            <div className="flex-1 min-w-0 max-w-2xl">
              <div className="flex items-start gap-3">
                <div className="flex-1">
                  <div className="text-gray-100 font-mono text-xs leading-relaxed" title={formula}>
                    {formula}
                  </div>
                </div>
                <div className="flex-1 border-l border-cyan-500/30 pl-3">
                  <div className="text-[9px] text-amber-400 font-semibold uppercase tracking-wide mb-0.5">Summary</div>
                  <div className="text-gray-200 text-[11px] leading-snug">{description}</div>
                  {cosmicLink.significance > 0.3 && (
                    <div className="flex items-center gap-1 mt-1">
                      <Sparkles className="w-3 h-3 text-purple-400" />
                      <span className="text-purple-300 text-[9px]">{cosmicLink.relationship}</span>
                    </div>
                  )}
                </div>
              </div>
            </div>
            <div className="h-10 w-px bg-cyan-500/40" />
            {/* Educational Summary Toggle */}
            <button
              onClick={() => setShowSummary(!showSummary)}
              className={`flex items-center gap-1 px-2 py-1.5 rounded-md transition-colors ${
                showSummary 
                  ? 'bg-emerald-600/40 border border-emerald-500/50' 
                  : 'bg-slate-700 hover:bg-slate-600 border border-slate-600'
              }`}
              title="Toggle educational summary"
            >
              <BookOpen className={`w-4 h-4 ${showSummary ? 'text-emerald-300' : 'text-gray-300'}`} />
              <span className={`text-[10px] font-medium ${showSummary ? 'text-emerald-200' : 'text-gray-300'}`}>
                Learn
              </span>
              <ChevronRight className={`w-3 h-3 transition-transform ${showSummary ? 'rotate-90 text-emerald-300' : 'text-gray-400'}`} />
            </button>
            <div className="h-10 w-px bg-cyan-500/40" />
            {/* Mesh Density Controls */}
            {onMeshDensityChange && (
              <>
                <div className="flex items-center gap-2">
                  <div className="text-[9px] text-amber-400 font-semibold uppercase">Mesh</div>
                  <div className="flex items-center gap-1">
                    <input
                      type="number"
                      value={parameters.uSegments}
                      onChange={(e) => onMeshDensityChange(Math.max(5, Math.min(300, parseInt(e.target.value) || 64)), parameters.vSegments)}
                      className="w-12 h-7 bg-slate-700 border border-amber-500/40 rounded text-center text-xs text-amber-200 focus:outline-none focus:border-amber-400"
                      min="5"
                      max="300"
                      title="U Segments (5-300)"
                    />
                    <span className="text-amber-500 text-xs">×</span>
                    <input
                      type="number"
                      value={parameters.vSegments}
                      onChange={(e) => onMeshDensityChange(parameters.uSegments, Math.max(5, Math.min(300, parseInt(e.target.value) || 48)))}
                      className="w-12 h-7 bg-slate-700 border border-amber-500/40 rounded text-center text-xs text-amber-200 focus:outline-none focus:border-amber-400"
                      min="5"
                      max="300"
                      title="V Segments (5-300)"
                    />
                  </div>
                </div>
                <div className="h-10 w-px bg-cyan-500/40" />
              </>
            )}
            <div ref={searchRef} className="relative">
              <div className="flex items-center bg-slate-700 rounded-md border border-slate-600 px-2 h-9 w-44">
                <Search className="w-3.5 h-3.5 text-gray-300 flex-shrink-0" />
                <input
                  ref={inputRef}
                  type="text"
                  value={searchQuery}
                  onChange={(e) => {
                    setSearchQuery(e.target.value);
                    setShowDropdown(true);
                  }}
                  onFocus={() => setShowDropdown(true)}
                  placeholder="Search shapes..."
                  className="flex-1 bg-transparent border-none outline-none text-gray-100 text-xs px-2 placeholder-gray-400"
                />
                {searchQuery && (
                  <button
                    onClick={() => {
                      setSearchQuery('');
                      inputRef.current?.focus();
                    }}
                    className="p-0.5 hover:bg-slate-600 rounded"
                  >
                    <X className="w-3 h-3 text-gray-300" />
                  </button>
                )}
              </div>

              {showDropdown && filteredShapes.length > 0 && (
                <div className="absolute bottom-full mb-1 left-0 w-72 bg-slate-800 rounded-lg border border-cyan-500/50 shadow-2xl overflow-hidden max-h-80 overflow-y-auto">
                  {filteredShapes.map((shape) => (
                    <button
                      key={shape}
                      onClick={() => handleShapeSelect(shape)}
                      className="w-full px-3 py-2 text-left hover:bg-cyan-600/40 transition-colors flex items-center gap-2 border-b border-slate-700 last:border-0"
                    >
                      <span className="text-gray-100 text-xs font-medium">{getShapeDisplayName(shape)}</span>
                      <span className="text-gray-400 text-[9px] truncate flex-1 text-right">{shape}</span>
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
          
          {/* Collapsible Educational Summary Panel */}
          {showSummary && (
            <div className="mt-2 bg-gradient-to-br from-slate-800 to-slate-900 rounded-lg border border-emerald-500/40 shadow-xl overflow-hidden animate-in slide-in-from-top-2 duration-200">
              <div className="px-4 py-3">
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <BookOpen className="w-4 h-4 text-emerald-400" />
                    <h3 className="text-emerald-300 font-bold text-sm">Educational Summary: {shapeName}</h3>
                  </div>
                  <button
                    onClick={() => setShowSummary(false)}
                    className="p-1 hover:bg-slate-700 rounded transition-colors"
                    title="Close summary"
                  >
                    <X className="w-4 h-4 text-gray-400 hover:text-gray-200" />
                  </button>
                </div>
                
                <div className="grid grid-cols-2 gap-3 text-xs">
                  <div className="bg-slate-700/50 rounded-lg p-3 border-l-2 border-blue-400">
                    <div className="text-blue-400 font-semibold uppercase text-[10px] tracking-wide mb-1.5">Origin & History</div>
                    <p className="text-gray-200 leading-relaxed"><HighlightedText text={shapeSummary.origin} /></p>
                  </div>
                  
                  <div className="bg-slate-700/50 rounded-lg p-3 border-l-2 border-purple-400">
                    <div className="text-purple-400 font-semibold uppercase text-[10px] tracking-wide mb-1.5">Mathematical Function</div>
                    <p className="text-gray-200 leading-relaxed"><HighlightedText text={shapeSummary.function} /></p>
                  </div>
                  
                  <div className="bg-slate-700/50 rounded-lg p-3 border-l-2 border-amber-400">
                    <div className="text-amber-400 font-semibold uppercase text-[10px] tracking-wide mb-1.5">Real-World Applications</div>
                    <p className="text-gray-200 leading-relaxed"><HighlightedText text={shapeSummary.applications} /></p>
                  </div>
                  
                  <div className="bg-slate-700/50 rounded-lg p-3 border-l-2 border-emerald-400">
                    <div className="text-emerald-400 font-semibold uppercase text-[10px] tracking-wide mb-1.5">Future Implementations</div>
                    <p className="text-gray-200 leading-relaxed"><HighlightedText text={shapeSummary.future} /></p>
                  </div>
                </div>
                
                <div className="mt-3 pt-2 border-t border-slate-700/50 flex items-center justify-between">
                  <span className="text-gray-500 text-[10px]">
                    Shape ID: <span className="text-gray-400 font-mono">{parameters.type}</span>
                  </span>
                  <span className="text-emerald-500/70 text-[10px]">
                    Part of Δmension Mathematical Universe
                  </span>
                </div>
              </div>
            </div>
          )}
        </div>
      ) : (
        <button
          onClick={() => setIsExpanded(true)}
          className="bg-slate-800 rounded-lg px-3 py-1.5 border border-cyan-500/50 shadow-xl flex items-center gap-2 hover:border-cyan-400 transition-all group"
          title="Click to expand formula"
        >
          <ChevronUp className="w-3.5 h-3.5 text-cyan-400 group-hover:text-cyan-300" />
          <span className="text-cyan-300 font-semibold text-xs">{shapeName}</span>
          <span className="text-gray-300 text-[10px]">• Click for formula</span>
        </button>
      )}
    </div>
  );
}
